// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: steammessages_econ.steamclient.proto

package com.jsteamkit.internals.proto;

public final class SteammessagesEconSteamclient {
  private SteammessagesEconSteamclient() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface CEcon_ClientGetItemShopOverlayAuthURL_RequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CEcon_ClientGetItemShopOverlayAuthURL_Request)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string return_url = 1;</code>
     */
    boolean hasReturnUrl();
    /**
     * <code>optional string return_url = 1;</code>
     */
    java.lang.String getReturnUrl();
    /**
     * <code>optional string return_url = 1;</code>
     */
    com.google.protobuf.ByteString
        getReturnUrlBytes();
  }
  /**
   * Protobuf type {@code CEcon_ClientGetItemShopOverlayAuthURL_Request}
   */
  public static final class CEcon_ClientGetItemShopOverlayAuthURL_Request extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:CEcon_ClientGetItemShopOverlayAuthURL_Request)
      CEcon_ClientGetItemShopOverlayAuthURL_RequestOrBuilder {
    // Use CEcon_ClientGetItemShopOverlayAuthURL_Request.newBuilder() to construct.
    private CEcon_ClientGetItemShopOverlayAuthURL_Request(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CEcon_ClientGetItemShopOverlayAuthURL_Request(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CEcon_ClientGetItemShopOverlayAuthURL_Request defaultInstance;
    public static CEcon_ClientGetItemShopOverlayAuthURL_Request getDefaultInstance() {
      return defaultInstance;
    }

    public CEcon_ClientGetItemShopOverlayAuthURL_Request getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CEcon_ClientGetItemShopOverlayAuthURL_Request(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              returnUrl_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SteammessagesEconSteamclient.internal_static_CEcon_ClientGetItemShopOverlayAuthURL_Request_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SteammessagesEconSteamclient.internal_static_CEcon_ClientGetItemShopOverlayAuthURL_Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SteammessagesEconSteamclient.CEcon_ClientGetItemShopOverlayAuthURL_Request.class, SteammessagesEconSteamclient.CEcon_ClientGetItemShopOverlayAuthURL_Request.Builder.class);
    }

    public static com.google.protobuf.Parser<CEcon_ClientGetItemShopOverlayAuthURL_Request> PARSER =
        new com.google.protobuf.AbstractParser<CEcon_ClientGetItemShopOverlayAuthURL_Request>() {
      public CEcon_ClientGetItemShopOverlayAuthURL_Request parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CEcon_ClientGetItemShopOverlayAuthURL_Request(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CEcon_ClientGetItemShopOverlayAuthURL_Request> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int RETURN_URL_FIELD_NUMBER = 1;
    private java.lang.Object returnUrl_;
    /**
     * <code>optional string return_url = 1;</code>
     */
    public boolean hasReturnUrl() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string return_url = 1;</code>
     */
    public java.lang.String getReturnUrl() {
      java.lang.Object ref = returnUrl_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          returnUrl_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string return_url = 1;</code>
     */
    public com.google.protobuf.ByteString
        getReturnUrlBytes() {
      java.lang.Object ref = returnUrl_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        returnUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      returnUrl_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getReturnUrlBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getReturnUrlBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static SteammessagesEconSteamclient.CEcon_ClientGetItemShopOverlayAuthURL_Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SteammessagesEconSteamclient.CEcon_ClientGetItemShopOverlayAuthURL_Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SteammessagesEconSteamclient.CEcon_ClientGetItemShopOverlayAuthURL_Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SteammessagesEconSteamclient.CEcon_ClientGetItemShopOverlayAuthURL_Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SteammessagesEconSteamclient.CEcon_ClientGetItemShopOverlayAuthURL_Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static SteammessagesEconSteamclient.CEcon_ClientGetItemShopOverlayAuthURL_Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static SteammessagesEconSteamclient.CEcon_ClientGetItemShopOverlayAuthURL_Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static SteammessagesEconSteamclient.CEcon_ClientGetItemShopOverlayAuthURL_Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static SteammessagesEconSteamclient.CEcon_ClientGetItemShopOverlayAuthURL_Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static SteammessagesEconSteamclient.CEcon_ClientGetItemShopOverlayAuthURL_Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(SteammessagesEconSteamclient.CEcon_ClientGetItemShopOverlayAuthURL_Request prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CEcon_ClientGetItemShopOverlayAuthURL_Request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CEcon_ClientGetItemShopOverlayAuthURL_Request)
        SteammessagesEconSteamclient.CEcon_ClientGetItemShopOverlayAuthURL_RequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SteammessagesEconSteamclient.internal_static_CEcon_ClientGetItemShopOverlayAuthURL_Request_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SteammessagesEconSteamclient.internal_static_CEcon_ClientGetItemShopOverlayAuthURL_Request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                SteammessagesEconSteamclient.CEcon_ClientGetItemShopOverlayAuthURL_Request.class, SteammessagesEconSteamclient.CEcon_ClientGetItemShopOverlayAuthURL_Request.Builder.class);
      }

      // Construct using SteammessagesEconSteamclient.CEcon_ClientGetItemShopOverlayAuthURL_Request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        returnUrl_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SteammessagesEconSteamclient.internal_static_CEcon_ClientGetItemShopOverlayAuthURL_Request_descriptor;
      }

      public SteammessagesEconSteamclient.CEcon_ClientGetItemShopOverlayAuthURL_Request getDefaultInstanceForType() {
        return SteammessagesEconSteamclient.CEcon_ClientGetItemShopOverlayAuthURL_Request.getDefaultInstance();
      }

      public SteammessagesEconSteamclient.CEcon_ClientGetItemShopOverlayAuthURL_Request build() {
        SteammessagesEconSteamclient.CEcon_ClientGetItemShopOverlayAuthURL_Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public SteammessagesEconSteamclient.CEcon_ClientGetItemShopOverlayAuthURL_Request buildPartial() {
        SteammessagesEconSteamclient.CEcon_ClientGetItemShopOverlayAuthURL_Request result = new SteammessagesEconSteamclient.CEcon_ClientGetItemShopOverlayAuthURL_Request(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.returnUrl_ = returnUrl_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof SteammessagesEconSteamclient.CEcon_ClientGetItemShopOverlayAuthURL_Request) {
          return mergeFrom((SteammessagesEconSteamclient.CEcon_ClientGetItemShopOverlayAuthURL_Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(SteammessagesEconSteamclient.CEcon_ClientGetItemShopOverlayAuthURL_Request other) {
        if (other == SteammessagesEconSteamclient.CEcon_ClientGetItemShopOverlayAuthURL_Request.getDefaultInstance()) return this;
        if (other.hasReturnUrl()) {
          bitField0_ |= 0x00000001;
          returnUrl_ = other.returnUrl_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        SteammessagesEconSteamclient.CEcon_ClientGetItemShopOverlayAuthURL_Request parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (SteammessagesEconSteamclient.CEcon_ClientGetItemShopOverlayAuthURL_Request) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object returnUrl_ = "";
      /**
       * <code>optional string return_url = 1;</code>
       */
      public boolean hasReturnUrl() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string return_url = 1;</code>
       */
      public java.lang.String getReturnUrl() {
        java.lang.Object ref = returnUrl_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            returnUrl_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string return_url = 1;</code>
       */
      public com.google.protobuf.ByteString
          getReturnUrlBytes() {
        java.lang.Object ref = returnUrl_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          returnUrl_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string return_url = 1;</code>
       */
      public Builder setReturnUrl(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        returnUrl_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string return_url = 1;</code>
       */
      public Builder clearReturnUrl() {
        bitField0_ = (bitField0_ & ~0x00000001);
        returnUrl_ = getDefaultInstance().getReturnUrl();
        onChanged();
        return this;
      }
      /**
       * <code>optional string return_url = 1;</code>
       */
      public Builder setReturnUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        returnUrl_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:CEcon_ClientGetItemShopOverlayAuthURL_Request)
    }

    static {
      defaultInstance = new CEcon_ClientGetItemShopOverlayAuthURL_Request(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:CEcon_ClientGetItemShopOverlayAuthURL_Request)
  }

  public interface CEcon_ClientGetItemShopOverlayAuthURL_ResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CEcon_ClientGetItemShopOverlayAuthURL_Response)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string url = 1;</code>
     */
    boolean hasUrl();
    /**
     * <code>optional string url = 1;</code>
     */
    java.lang.String getUrl();
    /**
     * <code>optional string url = 1;</code>
     */
    com.google.protobuf.ByteString
        getUrlBytes();
  }
  /**
   * Protobuf type {@code CEcon_ClientGetItemShopOverlayAuthURL_Response}
   */
  public static final class CEcon_ClientGetItemShopOverlayAuthURL_Response extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:CEcon_ClientGetItemShopOverlayAuthURL_Response)
      CEcon_ClientGetItemShopOverlayAuthURL_ResponseOrBuilder {
    // Use CEcon_ClientGetItemShopOverlayAuthURL_Response.newBuilder() to construct.
    private CEcon_ClientGetItemShopOverlayAuthURL_Response(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CEcon_ClientGetItemShopOverlayAuthURL_Response(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CEcon_ClientGetItemShopOverlayAuthURL_Response defaultInstance;
    public static CEcon_ClientGetItemShopOverlayAuthURL_Response getDefaultInstance() {
      return defaultInstance;
    }

    public CEcon_ClientGetItemShopOverlayAuthURL_Response getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CEcon_ClientGetItemShopOverlayAuthURL_Response(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              url_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SteammessagesEconSteamclient.internal_static_CEcon_ClientGetItemShopOverlayAuthURL_Response_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SteammessagesEconSteamclient.internal_static_CEcon_ClientGetItemShopOverlayAuthURL_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SteammessagesEconSteamclient.CEcon_ClientGetItemShopOverlayAuthURL_Response.class, SteammessagesEconSteamclient.CEcon_ClientGetItemShopOverlayAuthURL_Response.Builder.class);
    }

    public static com.google.protobuf.Parser<CEcon_ClientGetItemShopOverlayAuthURL_Response> PARSER =
        new com.google.protobuf.AbstractParser<CEcon_ClientGetItemShopOverlayAuthURL_Response>() {
      public CEcon_ClientGetItemShopOverlayAuthURL_Response parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CEcon_ClientGetItemShopOverlayAuthURL_Response(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CEcon_ClientGetItemShopOverlayAuthURL_Response> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int URL_FIELD_NUMBER = 1;
    private java.lang.Object url_;
    /**
     * <code>optional string url = 1;</code>
     */
    public boolean hasUrl() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string url = 1;</code>
     */
    public java.lang.String getUrl() {
      java.lang.Object ref = url_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          url_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string url = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUrlBytes() {
      java.lang.Object ref = url_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        url_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      url_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getUrlBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getUrlBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static SteammessagesEconSteamclient.CEcon_ClientGetItemShopOverlayAuthURL_Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SteammessagesEconSteamclient.CEcon_ClientGetItemShopOverlayAuthURL_Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SteammessagesEconSteamclient.CEcon_ClientGetItemShopOverlayAuthURL_Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SteammessagesEconSteamclient.CEcon_ClientGetItemShopOverlayAuthURL_Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SteammessagesEconSteamclient.CEcon_ClientGetItemShopOverlayAuthURL_Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static SteammessagesEconSteamclient.CEcon_ClientGetItemShopOverlayAuthURL_Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static SteammessagesEconSteamclient.CEcon_ClientGetItemShopOverlayAuthURL_Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static SteammessagesEconSteamclient.CEcon_ClientGetItemShopOverlayAuthURL_Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static SteammessagesEconSteamclient.CEcon_ClientGetItemShopOverlayAuthURL_Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static SteammessagesEconSteamclient.CEcon_ClientGetItemShopOverlayAuthURL_Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(SteammessagesEconSteamclient.CEcon_ClientGetItemShopOverlayAuthURL_Response prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CEcon_ClientGetItemShopOverlayAuthURL_Response}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CEcon_ClientGetItemShopOverlayAuthURL_Response)
        SteammessagesEconSteamclient.CEcon_ClientGetItemShopOverlayAuthURL_ResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SteammessagesEconSteamclient.internal_static_CEcon_ClientGetItemShopOverlayAuthURL_Response_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SteammessagesEconSteamclient.internal_static_CEcon_ClientGetItemShopOverlayAuthURL_Response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                SteammessagesEconSteamclient.CEcon_ClientGetItemShopOverlayAuthURL_Response.class, SteammessagesEconSteamclient.CEcon_ClientGetItemShopOverlayAuthURL_Response.Builder.class);
      }

      // Construct using SteammessagesEconSteamclient.CEcon_ClientGetItemShopOverlayAuthURL_Response.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        url_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SteammessagesEconSteamclient.internal_static_CEcon_ClientGetItemShopOverlayAuthURL_Response_descriptor;
      }

      public SteammessagesEconSteamclient.CEcon_ClientGetItemShopOverlayAuthURL_Response getDefaultInstanceForType() {
        return SteammessagesEconSteamclient.CEcon_ClientGetItemShopOverlayAuthURL_Response.getDefaultInstance();
      }

      public SteammessagesEconSteamclient.CEcon_ClientGetItemShopOverlayAuthURL_Response build() {
        SteammessagesEconSteamclient.CEcon_ClientGetItemShopOverlayAuthURL_Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public SteammessagesEconSteamclient.CEcon_ClientGetItemShopOverlayAuthURL_Response buildPartial() {
        SteammessagesEconSteamclient.CEcon_ClientGetItemShopOverlayAuthURL_Response result = new SteammessagesEconSteamclient.CEcon_ClientGetItemShopOverlayAuthURL_Response(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.url_ = url_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof SteammessagesEconSteamclient.CEcon_ClientGetItemShopOverlayAuthURL_Response) {
          return mergeFrom((SteammessagesEconSteamclient.CEcon_ClientGetItemShopOverlayAuthURL_Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(SteammessagesEconSteamclient.CEcon_ClientGetItemShopOverlayAuthURL_Response other) {
        if (other == SteammessagesEconSteamclient.CEcon_ClientGetItemShopOverlayAuthURL_Response.getDefaultInstance()) return this;
        if (other.hasUrl()) {
          bitField0_ |= 0x00000001;
          url_ = other.url_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        SteammessagesEconSteamclient.CEcon_ClientGetItemShopOverlayAuthURL_Response parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (SteammessagesEconSteamclient.CEcon_ClientGetItemShopOverlayAuthURL_Response) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object url_ = "";
      /**
       * <code>optional string url = 1;</code>
       */
      public boolean hasUrl() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string url = 1;</code>
       */
      public java.lang.String getUrl() {
        java.lang.Object ref = url_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            url_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string url = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUrlBytes() {
        java.lang.Object ref = url_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          url_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string url = 1;</code>
       */
      public Builder setUrl(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        url_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string url = 1;</code>
       */
      public Builder clearUrl() {
        bitField0_ = (bitField0_ & ~0x00000001);
        url_ = getDefaultInstance().getUrl();
        onChanged();
        return this;
      }
      /**
       * <code>optional string url = 1;</code>
       */
      public Builder setUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        url_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:CEcon_ClientGetItemShopOverlayAuthURL_Response)
    }

    static {
      defaultInstance = new CEcon_ClientGetItemShopOverlayAuthURL_Response(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:CEcon_ClientGetItemShopOverlayAuthURL_Response)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CEcon_ClientGetItemShopOverlayAuthURL_Request_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CEcon_ClientGetItemShopOverlayAuthURL_Request_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CEcon_ClientGetItemShopOverlayAuthURL_Response_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CEcon_ClientGetItemShopOverlayAuthURL_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n$steammessages_econ.steamclient.proto\032," +
      "steammessages_unified_base.steamclient.p" +
      "roto\"C\n-CEcon_ClientGetItemShopOverlayAu" +
      "thURL_Request\022\022\n\nreturn_url\030\001 \001(\t\"=\n.CEc" +
      "on_ClientGetItemShopOverlayAuthURL_Respo" +
      "nse\022\013\n\003url\030\001 \001(\t2\243\002\n\004Econ\022\331\001\n\037ClientGetI" +
      "temShopOverlayAuthURL\022..CEcon_ClientGetI" +
      "temShopOverlayAuthURL_Request\032/.CEcon_Cl" +
      "ientGetItemShopOverlayAuthURL_Response\"U" +
      "\202\265\030QGenerates a URL which sets a secure ",
      "cookie for in-game-browser itemshop purc" +
      "hases\032?\202\265\030;A service that provides commu" +
      "nication with the econ serversB\003\200\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          SteammessagesUnifiedBaseSteamclient.getDescriptor(),
        }, assigner);
    internal_static_CEcon_ClientGetItemShopOverlayAuthURL_Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CEcon_ClientGetItemShopOverlayAuthURL_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_CEcon_ClientGetItemShopOverlayAuthURL_Request_descriptor,
        new java.lang.String[] { "ReturnUrl", });
    internal_static_CEcon_ClientGetItemShopOverlayAuthURL_Response_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_CEcon_ClientGetItemShopOverlayAuthURL_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_CEcon_ClientGetItemShopOverlayAuthURL_Response_descriptor,
        new java.lang.String[] { "Url", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(SteammessagesUnifiedBaseSteamclient.methodDescription);
    registry.add(SteammessagesUnifiedBaseSteamclient.serviceDescription);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    SteammessagesUnifiedBaseSteamclient.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
