// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: steammessages_video.steamclient.proto

package com.jsteamkit.internals.proto;

public final class SteammessagesVideoSteamclient {
  private SteammessagesVideoSteamclient() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface CVideo_ClientGetVideoURL_RequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CVideo_ClientGetVideoURL_Request)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional uint64 video_id = 1;</code>
     */
    boolean hasVideoId();
    /**
     * <code>optional uint64 video_id = 1;</code>
     */
    long getVideoId();

    /**
     * <code>optional uint32 client_cellid = 2;</code>
     */
    boolean hasClientCellid();
    /**
     * <code>optional uint32 client_cellid = 2;</code>
     */
    int getClientCellid();
  }
  /**
   * Protobuf type {@code CVideo_ClientGetVideoURL_Request}
   */
  public static final class CVideo_ClientGetVideoURL_Request extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:CVideo_ClientGetVideoURL_Request)
      CVideo_ClientGetVideoURL_RequestOrBuilder {
    // Use CVideo_ClientGetVideoURL_Request.newBuilder() to construct.
    private CVideo_ClientGetVideoURL_Request(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CVideo_ClientGetVideoURL_Request(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CVideo_ClientGetVideoURL_Request defaultInstance;
    public static CVideo_ClientGetVideoURL_Request getDefaultInstance() {
      return defaultInstance;
    }

    public CVideo_ClientGetVideoURL_Request getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CVideo_ClientGetVideoURL_Request(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              videoId_ = input.readUInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              clientCellid_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SteammessagesVideoSteamclient.internal_static_CVideo_ClientGetVideoURL_Request_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SteammessagesVideoSteamclient.internal_static_CVideo_ClientGetVideoURL_Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SteammessagesVideoSteamclient.CVideo_ClientGetVideoURL_Request.class, SteammessagesVideoSteamclient.CVideo_ClientGetVideoURL_Request.Builder.class);
    }

    public static com.google.protobuf.Parser<CVideo_ClientGetVideoURL_Request> PARSER =
        new com.google.protobuf.AbstractParser<CVideo_ClientGetVideoURL_Request>() {
      public CVideo_ClientGetVideoURL_Request parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CVideo_ClientGetVideoURL_Request(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CVideo_ClientGetVideoURL_Request> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int VIDEO_ID_FIELD_NUMBER = 1;
    private long videoId_;
    /**
     * <code>optional uint64 video_id = 1;</code>
     */
    public boolean hasVideoId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional uint64 video_id = 1;</code>
     */
    public long getVideoId() {
      return videoId_;
    }

    public static final int CLIENT_CELLID_FIELD_NUMBER = 2;
    private int clientCellid_;
    /**
     * <code>optional uint32 client_cellid = 2;</code>
     */
    public boolean hasClientCellid() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional uint32 client_cellid = 2;</code>
     */
    public int getClientCellid() {
      return clientCellid_;
    }

    private void initFields() {
      videoId_ = 0L;
      clientCellid_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt64(1, videoId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, clientCellid_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, videoId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, clientCellid_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static SteammessagesVideoSteamclient.CVideo_ClientGetVideoURL_Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SteammessagesVideoSteamclient.CVideo_ClientGetVideoURL_Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SteammessagesVideoSteamclient.CVideo_ClientGetVideoURL_Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SteammessagesVideoSteamclient.CVideo_ClientGetVideoURL_Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SteammessagesVideoSteamclient.CVideo_ClientGetVideoURL_Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static SteammessagesVideoSteamclient.CVideo_ClientGetVideoURL_Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static SteammessagesVideoSteamclient.CVideo_ClientGetVideoURL_Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static SteammessagesVideoSteamclient.CVideo_ClientGetVideoURL_Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static SteammessagesVideoSteamclient.CVideo_ClientGetVideoURL_Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static SteammessagesVideoSteamclient.CVideo_ClientGetVideoURL_Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(SteammessagesVideoSteamclient.CVideo_ClientGetVideoURL_Request prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CVideo_ClientGetVideoURL_Request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CVideo_ClientGetVideoURL_Request)
        SteammessagesVideoSteamclient.CVideo_ClientGetVideoURL_RequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SteammessagesVideoSteamclient.internal_static_CVideo_ClientGetVideoURL_Request_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SteammessagesVideoSteamclient.internal_static_CVideo_ClientGetVideoURL_Request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                SteammessagesVideoSteamclient.CVideo_ClientGetVideoURL_Request.class, SteammessagesVideoSteamclient.CVideo_ClientGetVideoURL_Request.Builder.class);
      }

      // Construct using SteammessagesVideoSteamclient.CVideo_ClientGetVideoURL_Request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        videoId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        clientCellid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SteammessagesVideoSteamclient.internal_static_CVideo_ClientGetVideoURL_Request_descriptor;
      }

      public SteammessagesVideoSteamclient.CVideo_ClientGetVideoURL_Request getDefaultInstanceForType() {
        return SteammessagesVideoSteamclient.CVideo_ClientGetVideoURL_Request.getDefaultInstance();
      }

      public SteammessagesVideoSteamclient.CVideo_ClientGetVideoURL_Request build() {
        SteammessagesVideoSteamclient.CVideo_ClientGetVideoURL_Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public SteammessagesVideoSteamclient.CVideo_ClientGetVideoURL_Request buildPartial() {
        SteammessagesVideoSteamclient.CVideo_ClientGetVideoURL_Request result = new SteammessagesVideoSteamclient.CVideo_ClientGetVideoURL_Request(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.videoId_ = videoId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.clientCellid_ = clientCellid_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof SteammessagesVideoSteamclient.CVideo_ClientGetVideoURL_Request) {
          return mergeFrom((SteammessagesVideoSteamclient.CVideo_ClientGetVideoURL_Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(SteammessagesVideoSteamclient.CVideo_ClientGetVideoURL_Request other) {
        if (other == SteammessagesVideoSteamclient.CVideo_ClientGetVideoURL_Request.getDefaultInstance()) return this;
        if (other.hasVideoId()) {
          setVideoId(other.getVideoId());
        }
        if (other.hasClientCellid()) {
          setClientCellid(other.getClientCellid());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        SteammessagesVideoSteamclient.CVideo_ClientGetVideoURL_Request parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (SteammessagesVideoSteamclient.CVideo_ClientGetVideoURL_Request) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long videoId_ ;
      /**
       * <code>optional uint64 video_id = 1;</code>
       */
      public boolean hasVideoId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional uint64 video_id = 1;</code>
       */
      public long getVideoId() {
        return videoId_;
      }
      /**
       * <code>optional uint64 video_id = 1;</code>
       */
      public Builder setVideoId(long value) {
        bitField0_ |= 0x00000001;
        videoId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 video_id = 1;</code>
       */
      public Builder clearVideoId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        videoId_ = 0L;
        onChanged();
        return this;
      }

      private int clientCellid_ ;
      /**
       * <code>optional uint32 client_cellid = 2;</code>
       */
      public boolean hasClientCellid() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional uint32 client_cellid = 2;</code>
       */
      public int getClientCellid() {
        return clientCellid_;
      }
      /**
       * <code>optional uint32 client_cellid = 2;</code>
       */
      public Builder setClientCellid(int value) {
        bitField0_ |= 0x00000002;
        clientCellid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 client_cellid = 2;</code>
       */
      public Builder clearClientCellid() {
        bitField0_ = (bitField0_ & ~0x00000002);
        clientCellid_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:CVideo_ClientGetVideoURL_Request)
    }

    static {
      defaultInstance = new CVideo_ClientGetVideoURL_Request(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:CVideo_ClientGetVideoURL_Request)
  }

  public interface CVideo_ClientGetVideoURL_ResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CVideo_ClientGetVideoURL_Response)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional uint64 video_id = 1;</code>
     */
    boolean hasVideoId();
    /**
     * <code>optional uint64 video_id = 1;</code>
     */
    long getVideoId();

    /**
     * <code>optional string video_url = 2;</code>
     */
    boolean hasVideoUrl();
    /**
     * <code>optional string video_url = 2;</code>
     */
    java.lang.String getVideoUrl();
    /**
     * <code>optional string video_url = 2;</code>
     */
    com.google.protobuf.ByteString
        getVideoUrlBytes();
  }
  /**
   * Protobuf type {@code CVideo_ClientGetVideoURL_Response}
   */
  public static final class CVideo_ClientGetVideoURL_Response extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:CVideo_ClientGetVideoURL_Response)
      CVideo_ClientGetVideoURL_ResponseOrBuilder {
    // Use CVideo_ClientGetVideoURL_Response.newBuilder() to construct.
    private CVideo_ClientGetVideoURL_Response(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CVideo_ClientGetVideoURL_Response(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CVideo_ClientGetVideoURL_Response defaultInstance;
    public static CVideo_ClientGetVideoURL_Response getDefaultInstance() {
      return defaultInstance;
    }

    public CVideo_ClientGetVideoURL_Response getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CVideo_ClientGetVideoURL_Response(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              videoId_ = input.readUInt64();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              videoUrl_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SteammessagesVideoSteamclient.internal_static_CVideo_ClientGetVideoURL_Response_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SteammessagesVideoSteamclient.internal_static_CVideo_ClientGetVideoURL_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SteammessagesVideoSteamclient.CVideo_ClientGetVideoURL_Response.class, SteammessagesVideoSteamclient.CVideo_ClientGetVideoURL_Response.Builder.class);
    }

    public static com.google.protobuf.Parser<CVideo_ClientGetVideoURL_Response> PARSER =
        new com.google.protobuf.AbstractParser<CVideo_ClientGetVideoURL_Response>() {
      public CVideo_ClientGetVideoURL_Response parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CVideo_ClientGetVideoURL_Response(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CVideo_ClientGetVideoURL_Response> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int VIDEO_ID_FIELD_NUMBER = 1;
    private long videoId_;
    /**
     * <code>optional uint64 video_id = 1;</code>
     */
    public boolean hasVideoId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional uint64 video_id = 1;</code>
     */
    public long getVideoId() {
      return videoId_;
    }

    public static final int VIDEO_URL_FIELD_NUMBER = 2;
    private java.lang.Object videoUrl_;
    /**
     * <code>optional string video_url = 2;</code>
     */
    public boolean hasVideoUrl() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string video_url = 2;</code>
     */
    public java.lang.String getVideoUrl() {
      java.lang.Object ref = videoUrl_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          videoUrl_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string video_url = 2;</code>
     */
    public com.google.protobuf.ByteString
        getVideoUrlBytes() {
      java.lang.Object ref = videoUrl_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        videoUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      videoId_ = 0L;
      videoUrl_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt64(1, videoId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getVideoUrlBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, videoId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getVideoUrlBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static SteammessagesVideoSteamclient.CVideo_ClientGetVideoURL_Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SteammessagesVideoSteamclient.CVideo_ClientGetVideoURL_Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SteammessagesVideoSteamclient.CVideo_ClientGetVideoURL_Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SteammessagesVideoSteamclient.CVideo_ClientGetVideoURL_Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SteammessagesVideoSteamclient.CVideo_ClientGetVideoURL_Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static SteammessagesVideoSteamclient.CVideo_ClientGetVideoURL_Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static SteammessagesVideoSteamclient.CVideo_ClientGetVideoURL_Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static SteammessagesVideoSteamclient.CVideo_ClientGetVideoURL_Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static SteammessagesVideoSteamclient.CVideo_ClientGetVideoURL_Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static SteammessagesVideoSteamclient.CVideo_ClientGetVideoURL_Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(SteammessagesVideoSteamclient.CVideo_ClientGetVideoURL_Response prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CVideo_ClientGetVideoURL_Response}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CVideo_ClientGetVideoURL_Response)
        SteammessagesVideoSteamclient.CVideo_ClientGetVideoURL_ResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SteammessagesVideoSteamclient.internal_static_CVideo_ClientGetVideoURL_Response_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SteammessagesVideoSteamclient.internal_static_CVideo_ClientGetVideoURL_Response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                SteammessagesVideoSteamclient.CVideo_ClientGetVideoURL_Response.class, SteammessagesVideoSteamclient.CVideo_ClientGetVideoURL_Response.Builder.class);
      }

      // Construct using SteammessagesVideoSteamclient.CVideo_ClientGetVideoURL_Response.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        videoId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        videoUrl_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SteammessagesVideoSteamclient.internal_static_CVideo_ClientGetVideoURL_Response_descriptor;
      }

      public SteammessagesVideoSteamclient.CVideo_ClientGetVideoURL_Response getDefaultInstanceForType() {
        return SteammessagesVideoSteamclient.CVideo_ClientGetVideoURL_Response.getDefaultInstance();
      }

      public SteammessagesVideoSteamclient.CVideo_ClientGetVideoURL_Response build() {
        SteammessagesVideoSteamclient.CVideo_ClientGetVideoURL_Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public SteammessagesVideoSteamclient.CVideo_ClientGetVideoURL_Response buildPartial() {
        SteammessagesVideoSteamclient.CVideo_ClientGetVideoURL_Response result = new SteammessagesVideoSteamclient.CVideo_ClientGetVideoURL_Response(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.videoId_ = videoId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.videoUrl_ = videoUrl_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof SteammessagesVideoSteamclient.CVideo_ClientGetVideoURL_Response) {
          return mergeFrom((SteammessagesVideoSteamclient.CVideo_ClientGetVideoURL_Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(SteammessagesVideoSteamclient.CVideo_ClientGetVideoURL_Response other) {
        if (other == SteammessagesVideoSteamclient.CVideo_ClientGetVideoURL_Response.getDefaultInstance()) return this;
        if (other.hasVideoId()) {
          setVideoId(other.getVideoId());
        }
        if (other.hasVideoUrl()) {
          bitField0_ |= 0x00000002;
          videoUrl_ = other.videoUrl_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        SteammessagesVideoSteamclient.CVideo_ClientGetVideoURL_Response parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (SteammessagesVideoSteamclient.CVideo_ClientGetVideoURL_Response) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long videoId_ ;
      /**
       * <code>optional uint64 video_id = 1;</code>
       */
      public boolean hasVideoId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional uint64 video_id = 1;</code>
       */
      public long getVideoId() {
        return videoId_;
      }
      /**
       * <code>optional uint64 video_id = 1;</code>
       */
      public Builder setVideoId(long value) {
        bitField0_ |= 0x00000001;
        videoId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 video_id = 1;</code>
       */
      public Builder clearVideoId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        videoId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object videoUrl_ = "";
      /**
       * <code>optional string video_url = 2;</code>
       */
      public boolean hasVideoUrl() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string video_url = 2;</code>
       */
      public java.lang.String getVideoUrl() {
        java.lang.Object ref = videoUrl_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            videoUrl_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string video_url = 2;</code>
       */
      public com.google.protobuf.ByteString
          getVideoUrlBytes() {
        java.lang.Object ref = videoUrl_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          videoUrl_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string video_url = 2;</code>
       */
      public Builder setVideoUrl(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        videoUrl_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string video_url = 2;</code>
       */
      public Builder clearVideoUrl() {
        bitField0_ = (bitField0_ & ~0x00000002);
        videoUrl_ = getDefaultInstance().getVideoUrl();
        onChanged();
        return this;
      }
      /**
       * <code>optional string video_url = 2;</code>
       */
      public Builder setVideoUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        videoUrl_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:CVideo_ClientGetVideoURL_Response)
    }

    static {
      defaultInstance = new CVideo_ClientGetVideoURL_Response(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:CVideo_ClientGetVideoURL_Response)
  }

  public interface CVideo_UnlockedH264_NotificationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CVideo_UnlockedH264_Notification)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bytes encryption_key = 1;</code>
     */
    boolean hasEncryptionKey();
    /**
     * <code>optional bytes encryption_key = 1;</code>
     */
    com.google.protobuf.ByteString getEncryptionKey();
  }
  /**
   * Protobuf type {@code CVideo_UnlockedH264_Notification}
   */
  public static final class CVideo_UnlockedH264_Notification extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:CVideo_UnlockedH264_Notification)
      CVideo_UnlockedH264_NotificationOrBuilder {
    // Use CVideo_UnlockedH264_Notification.newBuilder() to construct.
    private CVideo_UnlockedH264_Notification(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CVideo_UnlockedH264_Notification(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CVideo_UnlockedH264_Notification defaultInstance;
    public static CVideo_UnlockedH264_Notification getDefaultInstance() {
      return defaultInstance;
    }

    public CVideo_UnlockedH264_Notification getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CVideo_UnlockedH264_Notification(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              encryptionKey_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SteammessagesVideoSteamclient.internal_static_CVideo_UnlockedH264_Notification_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SteammessagesVideoSteamclient.internal_static_CVideo_UnlockedH264_Notification_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SteammessagesVideoSteamclient.CVideo_UnlockedH264_Notification.class, SteammessagesVideoSteamclient.CVideo_UnlockedH264_Notification.Builder.class);
    }

    public static com.google.protobuf.Parser<CVideo_UnlockedH264_Notification> PARSER =
        new com.google.protobuf.AbstractParser<CVideo_UnlockedH264_Notification>() {
      public CVideo_UnlockedH264_Notification parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CVideo_UnlockedH264_Notification(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CVideo_UnlockedH264_Notification> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ENCRYPTION_KEY_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString encryptionKey_;
    /**
     * <code>optional bytes encryption_key = 1;</code>
     */
    public boolean hasEncryptionKey() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional bytes encryption_key = 1;</code>
     */
    public com.google.protobuf.ByteString getEncryptionKey() {
      return encryptionKey_;
    }

    private void initFields() {
      encryptionKey_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, encryptionKey_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, encryptionKey_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static SteammessagesVideoSteamclient.CVideo_UnlockedH264_Notification parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SteammessagesVideoSteamclient.CVideo_UnlockedH264_Notification parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SteammessagesVideoSteamclient.CVideo_UnlockedH264_Notification parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SteammessagesVideoSteamclient.CVideo_UnlockedH264_Notification parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SteammessagesVideoSteamclient.CVideo_UnlockedH264_Notification parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static SteammessagesVideoSteamclient.CVideo_UnlockedH264_Notification parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static SteammessagesVideoSteamclient.CVideo_UnlockedH264_Notification parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static SteammessagesVideoSteamclient.CVideo_UnlockedH264_Notification parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static SteammessagesVideoSteamclient.CVideo_UnlockedH264_Notification parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static SteammessagesVideoSteamclient.CVideo_UnlockedH264_Notification parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(SteammessagesVideoSteamclient.CVideo_UnlockedH264_Notification prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CVideo_UnlockedH264_Notification}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CVideo_UnlockedH264_Notification)
        SteammessagesVideoSteamclient.CVideo_UnlockedH264_NotificationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SteammessagesVideoSteamclient.internal_static_CVideo_UnlockedH264_Notification_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SteammessagesVideoSteamclient.internal_static_CVideo_UnlockedH264_Notification_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                SteammessagesVideoSteamclient.CVideo_UnlockedH264_Notification.class, SteammessagesVideoSteamclient.CVideo_UnlockedH264_Notification.Builder.class);
      }

      // Construct using SteammessagesVideoSteamclient.CVideo_UnlockedH264_Notification.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        encryptionKey_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SteammessagesVideoSteamclient.internal_static_CVideo_UnlockedH264_Notification_descriptor;
      }

      public SteammessagesVideoSteamclient.CVideo_UnlockedH264_Notification getDefaultInstanceForType() {
        return SteammessagesVideoSteamclient.CVideo_UnlockedH264_Notification.getDefaultInstance();
      }

      public SteammessagesVideoSteamclient.CVideo_UnlockedH264_Notification build() {
        SteammessagesVideoSteamclient.CVideo_UnlockedH264_Notification result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public SteammessagesVideoSteamclient.CVideo_UnlockedH264_Notification buildPartial() {
        SteammessagesVideoSteamclient.CVideo_UnlockedH264_Notification result = new SteammessagesVideoSteamclient.CVideo_UnlockedH264_Notification(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.encryptionKey_ = encryptionKey_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof SteammessagesVideoSteamclient.CVideo_UnlockedH264_Notification) {
          return mergeFrom((SteammessagesVideoSteamclient.CVideo_UnlockedH264_Notification)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(SteammessagesVideoSteamclient.CVideo_UnlockedH264_Notification other) {
        if (other == SteammessagesVideoSteamclient.CVideo_UnlockedH264_Notification.getDefaultInstance()) return this;
        if (other.hasEncryptionKey()) {
          setEncryptionKey(other.getEncryptionKey());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        SteammessagesVideoSteamclient.CVideo_UnlockedH264_Notification parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (SteammessagesVideoSteamclient.CVideo_UnlockedH264_Notification) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString encryptionKey_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes encryption_key = 1;</code>
       */
      public boolean hasEncryptionKey() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional bytes encryption_key = 1;</code>
       */
      public com.google.protobuf.ByteString getEncryptionKey() {
        return encryptionKey_;
      }
      /**
       * <code>optional bytes encryption_key = 1;</code>
       */
      public Builder setEncryptionKey(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        encryptionKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes encryption_key = 1;</code>
       */
      public Builder clearEncryptionKey() {
        bitField0_ = (bitField0_ & ~0x00000001);
        encryptionKey_ = getDefaultInstance().getEncryptionKey();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:CVideo_UnlockedH264_Notification)
    }

    static {
      defaultInstance = new CVideo_UnlockedH264_Notification(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:CVideo_UnlockedH264_Notification)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CVideo_ClientGetVideoURL_Request_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CVideo_ClientGetVideoURL_Request_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CVideo_ClientGetVideoURL_Response_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CVideo_ClientGetVideoURL_Response_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CVideo_UnlockedH264_Notification_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CVideo_UnlockedH264_Notification_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n%steammessages_video.steamclient.proto\032" +
      ",steammessages_unified_base.steamclient." +
      "proto\"\201\001\n CVideo_ClientGetVideoURL_Reque" +
      "st\022\036\n\010video_id\030\001 \001(\004B\014\202\265\030\010Video ID\022=\n\rcl" +
      "ient_cellid\030\002 \001(\rB&\202\265\030\"Cell ID of client" +
      ", zero if unknown\"r\n!CVideo_ClientGetVid" +
      "eoURL_Response\022\036\n\010video_id\030\001 \001(\004B\014\202\265\030\010Vi" +
      "deo ID\022-\n\tvideo_url\030\002 \001(\tB\032\202\265\030\026URL for getCode" +
      "ideo manifest\":\n CVideo_UnlockedH264_Not" +
      "ification\022\026\n\016encryption_key\030\001 \001(\0142\253\001\n\005Vi",
      "deo\022\216\001\n\021ClientGetVideoURL\022!.CVideo_Clien" +
      "tGetVideoURL_Request\032\".CVideo_ClientGetV" +
      "ideoURL_Response\"2\202\265\030.Get the initial UR" +
      "L to begin streaming a video\032\021\202\265\030\rVideo " +
      "methods2\236\001\n\013VideoClient\022\210\001\n\022NotifyUnlock" +
      "edH264\022!.CVideo_UnlockedH264_Notificatio" +
      "n\032\013.NoResponse\"B\202\265\030>Notification from se" +
      "rver to client that h264 has been unlock" +
      "ed\032\004\300\265\030\002B\003\200\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          SteammessagesUnifiedBaseSteamclient.getDescriptor(),
        }, assigner);
    internal_static_CVideo_ClientGetVideoURL_Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CVideo_ClientGetVideoURL_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_CVideo_ClientGetVideoURL_Request_descriptor,
        new java.lang.String[] { "VideoId", "ClientCellid", });
    internal_static_CVideo_ClientGetVideoURL_Response_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_CVideo_ClientGetVideoURL_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_CVideo_ClientGetVideoURL_Response_descriptor,
        new java.lang.String[] { "VideoId", "VideoUrl", });
    internal_static_CVideo_UnlockedH264_Notification_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_CVideo_UnlockedH264_Notification_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_CVideo_UnlockedH264_Notification_descriptor,
        new java.lang.String[] { "EncryptionKey", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(SteammessagesUnifiedBaseSteamclient.description);
    registry.add(SteammessagesUnifiedBaseSteamclient.description);
    registry.add(SteammessagesUnifiedBaseSteamclient.description);
    registry.add(SteammessagesUnifiedBaseSteamclient.description);
    registry.add(SteammessagesUnifiedBaseSteamclient.methodDescription);
    registry.add(SteammessagesUnifiedBaseSteamclient.serviceDescription);
    registry.add(SteammessagesUnifiedBaseSteamclient.methodDescription);
    registry.add(SteammessagesUnifiedBaseSteamclient.serviceExecutionSite);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    SteammessagesUnifiedBaseSteamclient.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
