// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: steammessages_datapublisher.steamclient.proto
package com.jsteamkit.internals.proto;

public final class SteammessagesDatapublisherSteamclient {
  private SteammessagesDatapublisherSteamclient() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CDataPublisher_ClientContentCorruptionReport_NotificationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CDataPublisher_ClientContentCorruptionReport_Notification)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional uint32 appid = 1;</code>
     */
    boolean hasAppid();
    /**
     * <code>optional uint32 appid = 1;</code>
     */
    int getAppid();

    /**
     * <code>optional uint32 depotid = 2;</code>
     */
    boolean hasDepotid();
    /**
     * <code>optional uint32 depotid = 2;</code>
     */
    int getDepotid();

    /**
     * <code>optional string download_source = 3 [(.description) = "host name of download source"];</code>
     */
    boolean hasDownloadSource();
    /**
     * <code>optional string download_source = 3 [(.description) = "host name of download source"];</code>
     */
    java.lang.String getDownloadSource();
    /**
     * <code>optional string download_source = 3 [(.description) = "host name of download source"];</code>
     */
    com.google.protobuf.ByteString
        getDownloadSourceBytes();

    /**
     * <code>optional string objectid = 4 [(.description) = "Chunk SHA or Manifest ID"];</code>
     */
    boolean hasObjectid();
    /**
     * <code>optional string objectid = 4 [(.description) = "Chunk SHA or Manifest ID"];</code>
     */
    java.lang.String getObjectid();
    /**
     * <code>optional string objectid = 4 [(.description) = "Chunk SHA or Manifest ID"];</code>
     */
    com.google.protobuf.ByteString
        getObjectidBytes();

    /**
     * <code>optional uint32 cellid = 5 [(.description) = "Client Cell ID"];</code>
     */
    boolean hasCellid();
    /**
     * <code>optional uint32 cellid = 5 [(.description) = "Client Cell ID"];</code>
     */
    int getCellid();

    /**
     * <code>optional bool is_manifest = 6 [(.description) = "The object is a manifest, not a chunk"];</code>
     */
    boolean hasIsManifest();
    /**
     * <code>optional bool is_manifest = 6 [(.description) = "The object is a manifest, not a chunk"];</code>
     */
    boolean getIsManifest();

    /**
     * <code>optional uint64 object_size = 7 [(.description) = "object size in bytes"];</code>
     */
    boolean hasObjectSize();
    /**
     * <code>optional uint64 object_size = 7 [(.description) = "object size in bytes"];</code>
     */
    long getObjectSize();

    /**
     * <code>optional uint32 corruption_type = 8 [(.description) = "See EContentCorruptionType"];</code>
     */
    boolean hasCorruptionType();
    /**
     * <code>optional uint32 corruption_type = 8 [(.description) = "See EContentCorruptionType"];</code>
     */
    int getCorruptionType();

    /**
     * <code>optional bool used_https = 9 [(.description) = "the request was HTTPS"];</code>
     */
    boolean hasUsedHttps();
    /**
     * <code>optional bool used_https = 9 [(.description) = "the request was HTTPS"];</code>
     */
    boolean getUsedHttps();
  }
  /**
   * Protobuf type {@code CDataPublisher_ClientContentCorruptionReport_Notification}
   */
  public  static final class CDataPublisher_ClientContentCorruptionReport_Notification extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:CDataPublisher_ClientContentCorruptionReport_Notification)
      CDataPublisher_ClientContentCorruptionReport_NotificationOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CDataPublisher_ClientContentCorruptionReport_Notification.newBuilder() to construct.
    private CDataPublisher_ClientContentCorruptionReport_Notification(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CDataPublisher_ClientContentCorruptionReport_Notification() {
      appid_ = 0;
      depotid_ = 0;
      downloadSource_ = "";
      objectid_ = "";
      cellid_ = 0;
      isManifest_ = false;
      objectSize_ = 0L;
      corruptionType_ = 0;
      usedHttps_ = false;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CDataPublisher_ClientContentCorruptionReport_Notification(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              appid_ = input.readUInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              depotid_ = input.readUInt32();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              downloadSource_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              objectid_ = bs;
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              cellid_ = input.readUInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              isManifest_ = input.readBool();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              objectSize_ = input.readUInt64();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              corruptionType_ = input.readUInt32();
              break;
            }
            case 72: {
              bitField0_ |= 0x00000100;
              usedHttps_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SteammessagesDatapublisherSteamclient.internal_static_CDataPublisher_ClientContentCorruptionReport_Notification_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SteammessagesDatapublisherSteamclient.internal_static_CDataPublisher_ClientContentCorruptionReport_Notification_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SteammessagesDatapublisherSteamclient.CDataPublisher_ClientContentCorruptionReport_Notification.class, SteammessagesDatapublisherSteamclient.CDataPublisher_ClientContentCorruptionReport_Notification.Builder.class);
    }

    private int bitField0_;
    public static final int APPID_FIELD_NUMBER = 1;
    private int appid_;
    /**
     * <code>optional uint32 appid = 1;</code>
     */
    public boolean hasAppid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional uint32 appid = 1;</code>
     */
    public int getAppid() {
      return appid_;
    }

    public static final int DEPOTID_FIELD_NUMBER = 2;
    private int depotid_;
    /**
     * <code>optional uint32 depotid = 2;</code>
     */
    public boolean hasDepotid() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional uint32 depotid = 2;</code>
     */
    public int getDepotid() {
      return depotid_;
    }

    public static final int DOWNLOAD_SOURCE_FIELD_NUMBER = 3;
    private volatile java.lang.Object downloadSource_;
    /**
     * <code>optional string download_source = 3 [(.description) = "host name of download source"];</code>
     */
    public boolean hasDownloadSource() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string download_source = 3 [(.description) = "host name of download source"];</code>
     */
    public java.lang.String getDownloadSource() {
      java.lang.Object ref = downloadSource_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          downloadSource_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string download_source = 3 [(.description) = "host name of download source"];</code>
     */
    public com.google.protobuf.ByteString
        getDownloadSourceBytes() {
      java.lang.Object ref = downloadSource_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        downloadSource_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int OBJECTID_FIELD_NUMBER = 4;
    private volatile java.lang.Object objectid_;
    /**
     * <code>optional string objectid = 4 [(.description) = "Chunk SHA or Manifest ID"];</code>
     */
    public boolean hasObjectid() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string objectid = 4 [(.description) = "Chunk SHA or Manifest ID"];</code>
     */
    public java.lang.String getObjectid() {
      java.lang.Object ref = objectid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          objectid_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string objectid = 4 [(.description) = "Chunk SHA or Manifest ID"];</code>
     */
    public com.google.protobuf.ByteString
        getObjectidBytes() {
      java.lang.Object ref = objectid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        objectid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CELLID_FIELD_NUMBER = 5;
    private int cellid_;
    /**
     * <code>optional uint32 cellid = 5 [(.description) = "Client Cell ID"];</code>
     */
    public boolean hasCellid() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional uint32 cellid = 5 [(.description) = "Client Cell ID"];</code>
     */
    public int getCellid() {
      return cellid_;
    }

    public static final int IS_MANIFEST_FIELD_NUMBER = 6;
    private boolean isManifest_;
    /**
     * <code>optional bool is_manifest = 6 [(.description) = "The object is a manifest, not a chunk"];</code>
     */
    public boolean hasIsManifest() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional bool is_manifest = 6 [(.description) = "The object is a manifest, not a chunk"];</code>
     */
    public boolean getIsManifest() {
      return isManifest_;
    }

    public static final int OBJECT_SIZE_FIELD_NUMBER = 7;
    private long objectSize_;
    /**
     * <code>optional uint64 object_size = 7 [(.description) = "object size in bytes"];</code>
     */
    public boolean hasObjectSize() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional uint64 object_size = 7 [(.description) = "object size in bytes"];</code>
     */
    public long getObjectSize() {
      return objectSize_;
    }

    public static final int CORRUPTION_TYPE_FIELD_NUMBER = 8;
    private int corruptionType_;
    /**
     * <code>optional uint32 corruption_type = 8 [(.description) = "See EContentCorruptionType"];</code>
     */
    public boolean hasCorruptionType() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional uint32 corruption_type = 8 [(.description) = "See EContentCorruptionType"];</code>
     */
    public int getCorruptionType() {
      return corruptionType_;
    }

    public static final int USED_HTTPS_FIELD_NUMBER = 9;
    private boolean usedHttps_;
    /**
     * <code>optional bool used_https = 9 [(.description) = "the request was HTTPS"];</code>
     */
    public boolean hasUsedHttps() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional bool used_https = 9 [(.description) = "the request was HTTPS"];</code>
     */
    public boolean getUsedHttps() {
      return usedHttps_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, appid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, depotid_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, downloadSource_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, objectid_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeUInt32(5, cellid_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBool(6, isManifest_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeUInt64(7, objectSize_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeUInt32(8, corruptionType_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeBool(9, usedHttps_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, appid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, depotid_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, downloadSource_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, objectid_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(5, cellid_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(6, isManifest_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(7, objectSize_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(8, corruptionType_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(9, usedHttps_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof SteammessagesDatapublisherSteamclient.CDataPublisher_ClientContentCorruptionReport_Notification)) {
        return super.equals(obj);
      }
      SteammessagesDatapublisherSteamclient.CDataPublisher_ClientContentCorruptionReport_Notification other = (SteammessagesDatapublisherSteamclient.CDataPublisher_ClientContentCorruptionReport_Notification) obj;

      boolean result = true;
      result = result && (hasAppid() == other.hasAppid());
      if (hasAppid()) {
        result = result && (getAppid()
            == other.getAppid());
      }
      result = result && (hasDepotid() == other.hasDepotid());
      if (hasDepotid()) {
        result = result && (getDepotid()
            == other.getDepotid());
      }
      result = result && (hasDownloadSource() == other.hasDownloadSource());
      if (hasDownloadSource()) {
        result = result && getDownloadSource()
            .equals(other.getDownloadSource());
      }
      result = result && (hasObjectid() == other.hasObjectid());
      if (hasObjectid()) {
        result = result && getObjectid()
            .equals(other.getObjectid());
      }
      result = result && (hasCellid() == other.hasCellid());
      if (hasCellid()) {
        result = result && (getCellid()
            == other.getCellid());
      }
      result = result && (hasIsManifest() == other.hasIsManifest());
      if (hasIsManifest()) {
        result = result && (getIsManifest()
            == other.getIsManifest());
      }
      result = result && (hasObjectSize() == other.hasObjectSize());
      if (hasObjectSize()) {
        result = result && (getObjectSize()
            == other.getObjectSize());
      }
      result = result && (hasCorruptionType() == other.hasCorruptionType());
      if (hasCorruptionType()) {
        result = result && (getCorruptionType()
            == other.getCorruptionType());
      }
      result = result && (hasUsedHttps() == other.hasUsedHttps());
      if (hasUsedHttps()) {
        result = result && (getUsedHttps()
            == other.getUsedHttps());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasAppid()) {
        hash = (37 * hash) + APPID_FIELD_NUMBER;
        hash = (53 * hash) + getAppid();
      }
      if (hasDepotid()) {
        hash = (37 * hash) + DEPOTID_FIELD_NUMBER;
        hash = (53 * hash) + getDepotid();
      }
      if (hasDownloadSource()) {
        hash = (37 * hash) + DOWNLOAD_SOURCE_FIELD_NUMBER;
        hash = (53 * hash) + getDownloadSource().hashCode();
      }
      if (hasObjectid()) {
        hash = (37 * hash) + OBJECTID_FIELD_NUMBER;
        hash = (53 * hash) + getObjectid().hashCode();
      }
      if (hasCellid()) {
        hash = (37 * hash) + CELLID_FIELD_NUMBER;
        hash = (53 * hash) + getCellid();
      }
      if (hasIsManifest()) {
        hash = (37 * hash) + IS_MANIFEST_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getIsManifest());
      }
      if (hasObjectSize()) {
        hash = (37 * hash) + OBJECT_SIZE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getObjectSize());
      }
      if (hasCorruptionType()) {
        hash = (37 * hash) + CORRUPTION_TYPE_FIELD_NUMBER;
        hash = (53 * hash) + getCorruptionType();
      }
      if (hasUsedHttps()) {
        hash = (37 * hash) + USED_HTTPS_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getUsedHttps());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static SteammessagesDatapublisherSteamclient.CDataPublisher_ClientContentCorruptionReport_Notification parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SteammessagesDatapublisherSteamclient.CDataPublisher_ClientContentCorruptionReport_Notification parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SteammessagesDatapublisherSteamclient.CDataPublisher_ClientContentCorruptionReport_Notification parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SteammessagesDatapublisherSteamclient.CDataPublisher_ClientContentCorruptionReport_Notification parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SteammessagesDatapublisherSteamclient.CDataPublisher_ClientContentCorruptionReport_Notification parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SteammessagesDatapublisherSteamclient.CDataPublisher_ClientContentCorruptionReport_Notification parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SteammessagesDatapublisherSteamclient.CDataPublisher_ClientContentCorruptionReport_Notification parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SteammessagesDatapublisherSteamclient.CDataPublisher_ClientContentCorruptionReport_Notification parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static SteammessagesDatapublisherSteamclient.CDataPublisher_ClientContentCorruptionReport_Notification parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static SteammessagesDatapublisherSteamclient.CDataPublisher_ClientContentCorruptionReport_Notification parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static SteammessagesDatapublisherSteamclient.CDataPublisher_ClientContentCorruptionReport_Notification parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SteammessagesDatapublisherSteamclient.CDataPublisher_ClientContentCorruptionReport_Notification parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(SteammessagesDatapublisherSteamclient.CDataPublisher_ClientContentCorruptionReport_Notification prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CDataPublisher_ClientContentCorruptionReport_Notification}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CDataPublisher_ClientContentCorruptionReport_Notification)
        SteammessagesDatapublisherSteamclient.CDataPublisher_ClientContentCorruptionReport_NotificationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SteammessagesDatapublisherSteamclient.internal_static_CDataPublisher_ClientContentCorruptionReport_Notification_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SteammessagesDatapublisherSteamclient.internal_static_CDataPublisher_ClientContentCorruptionReport_Notification_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                SteammessagesDatapublisherSteamclient.CDataPublisher_ClientContentCorruptionReport_Notification.class, SteammessagesDatapublisherSteamclient.CDataPublisher_ClientContentCorruptionReport_Notification.Builder.class);
      }

      // Construct using SteammessagesDatapublisherSteamclient.CDataPublisher_ClientContentCorruptionReport_Notification.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        appid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        depotid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        downloadSource_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        objectid_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        cellid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        isManifest_ = false;
        bitField0_ = (bitField0_ & ~0x00000020);
        objectSize_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000040);
        corruptionType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000080);
        usedHttps_ = false;
        bitField0_ = (bitField0_ & ~0x00000100);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SteammessagesDatapublisherSteamclient.internal_static_CDataPublisher_ClientContentCorruptionReport_Notification_descriptor;
      }

      public SteammessagesDatapublisherSteamclient.CDataPublisher_ClientContentCorruptionReport_Notification getDefaultInstanceForType() {
        return SteammessagesDatapublisherSteamclient.CDataPublisher_ClientContentCorruptionReport_Notification.getDefaultInstance();
      }

      public SteammessagesDatapublisherSteamclient.CDataPublisher_ClientContentCorruptionReport_Notification build() {
        SteammessagesDatapublisherSteamclient.CDataPublisher_ClientContentCorruptionReport_Notification result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public SteammessagesDatapublisherSteamclient.CDataPublisher_ClientContentCorruptionReport_Notification buildPartial() {
        SteammessagesDatapublisherSteamclient.CDataPublisher_ClientContentCorruptionReport_Notification result = new SteammessagesDatapublisherSteamclient.CDataPublisher_ClientContentCorruptionReport_Notification(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.appid_ = appid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.depotid_ = depotid_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.downloadSource_ = downloadSource_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.objectid_ = objectid_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.cellid_ = cellid_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.isManifest_ = isManifest_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.objectSize_ = objectSize_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.corruptionType_ = corruptionType_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.usedHttps_ = usedHttps_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof SteammessagesDatapublisherSteamclient.CDataPublisher_ClientContentCorruptionReport_Notification) {
          return mergeFrom((SteammessagesDatapublisherSteamclient.CDataPublisher_ClientContentCorruptionReport_Notification)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(SteammessagesDatapublisherSteamclient.CDataPublisher_ClientContentCorruptionReport_Notification other) {
        if (other == SteammessagesDatapublisherSteamclient.CDataPublisher_ClientContentCorruptionReport_Notification.getDefaultInstance()) return this;
        if (other.hasAppid()) {
          setAppid(other.getAppid());
        }
        if (other.hasDepotid()) {
          setDepotid(other.getDepotid());
        }
        if (other.hasDownloadSource()) {
          bitField0_ |= 0x00000004;
          downloadSource_ = other.downloadSource_;
          onChanged();
        }
        if (other.hasObjectid()) {
          bitField0_ |= 0x00000008;
          objectid_ = other.objectid_;
          onChanged();
        }
        if (other.hasCellid()) {
          setCellid(other.getCellid());
        }
        if (other.hasIsManifest()) {
          setIsManifest(other.getIsManifest());
        }
        if (other.hasObjectSize()) {
          setObjectSize(other.getObjectSize());
        }
        if (other.hasCorruptionType()) {
          setCorruptionType(other.getCorruptionType());
        }
        if (other.hasUsedHttps()) {
          setUsedHttps(other.getUsedHttps());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        SteammessagesDatapublisherSteamclient.CDataPublisher_ClientContentCorruptionReport_Notification parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (SteammessagesDatapublisherSteamclient.CDataPublisher_ClientContentCorruptionReport_Notification) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int appid_ ;
      /**
       * <code>optional uint32 appid = 1;</code>
       */
      public boolean hasAppid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional uint32 appid = 1;</code>
       */
      public int getAppid() {
        return appid_;
      }
      /**
       * <code>optional uint32 appid = 1;</code>
       */
      public Builder setAppid(int value) {
        bitField0_ |= 0x00000001;
        appid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 appid = 1;</code>
       */
      public Builder clearAppid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        appid_ = 0;
        onChanged();
        return this;
      }

      private int depotid_ ;
      /**
       * <code>optional uint32 depotid = 2;</code>
       */
      public boolean hasDepotid() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional uint32 depotid = 2;</code>
       */
      public int getDepotid() {
        return depotid_;
      }
      /**
       * <code>optional uint32 depotid = 2;</code>
       */
      public Builder setDepotid(int value) {
        bitField0_ |= 0x00000002;
        depotid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 depotid = 2;</code>
       */
      public Builder clearDepotid() {
        bitField0_ = (bitField0_ & ~0x00000002);
        depotid_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object downloadSource_ = "";
      /**
       * <code>optional string download_source = 3 [(.description) = "host name of download source"];</code>
       */
      public boolean hasDownloadSource() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string download_source = 3 [(.description) = "host name of download source"];</code>
       */
      public java.lang.String getDownloadSource() {
        java.lang.Object ref = downloadSource_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            downloadSource_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string download_source = 3 [(.description) = "host name of download source"];</code>
       */
      public com.google.protobuf.ByteString
          getDownloadSourceBytes() {
        java.lang.Object ref = downloadSource_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          downloadSource_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string download_source = 3 [(.description) = "host name of download source"];</code>
       */
      public Builder setDownloadSource(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        downloadSource_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string download_source = 3 [(.description) = "host name of download source"];</code>
       */
      public Builder clearDownloadSource() {
        bitField0_ = (bitField0_ & ~0x00000004);
        downloadSource_ = getDefaultInstance().getDownloadSource();
        onChanged();
        return this;
      }
      /**
       * <code>optional string download_source = 3 [(.description) = "host name of download source"];</code>
       */
      public Builder setDownloadSourceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        downloadSource_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object objectid_ = "";
      /**
       * <code>optional string objectid = 4 [(.description) = "Chunk SHA or Manifest ID"];</code>
       */
      public boolean hasObjectid() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string objectid = 4 [(.description) = "Chunk SHA or Manifest ID"];</code>
       */
      public java.lang.String getObjectid() {
        java.lang.Object ref = objectid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            objectid_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string objectid = 4 [(.description) = "Chunk SHA or Manifest ID"];</code>
       */
      public com.google.protobuf.ByteString
          getObjectidBytes() {
        java.lang.Object ref = objectid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          objectid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string objectid = 4 [(.description) = "Chunk SHA or Manifest ID"];</code>
       */
      public Builder setObjectid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        objectid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string objectid = 4 [(.description) = "Chunk SHA or Manifest ID"];</code>
       */
      public Builder clearObjectid() {
        bitField0_ = (bitField0_ & ~0x00000008);
        objectid_ = getDefaultInstance().getObjectid();
        onChanged();
        return this;
      }
      /**
       * <code>optional string objectid = 4 [(.description) = "Chunk SHA or Manifest ID"];</code>
       */
      public Builder setObjectidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        objectid_ = value;
        onChanged();
        return this;
      }

      private int cellid_ ;
      /**
       * <code>optional uint32 cellid = 5 [(.description) = "Client Cell ID"];</code>
       */
      public boolean hasCellid() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional uint32 cellid = 5 [(.description) = "Client Cell ID"];</code>
       */
      public int getCellid() {
        return cellid_;
      }
      /**
       * <code>optional uint32 cellid = 5 [(.description) = "Client Cell ID"];</code>
       */
      public Builder setCellid(int value) {
        bitField0_ |= 0x00000010;
        cellid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 cellid = 5 [(.description) = "Client Cell ID"];</code>
       */
      public Builder clearCellid() {
        bitField0_ = (bitField0_ & ~0x00000010);
        cellid_ = 0;
        onChanged();
        return this;
      }

      private boolean isManifest_ ;
      /**
       * <code>optional bool is_manifest = 6 [(.description) = "The object is a manifest, not a chunk"];</code>
       */
      public boolean hasIsManifest() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional bool is_manifest = 6 [(.description) = "The object is a manifest, not a chunk"];</code>
       */
      public boolean getIsManifest() {
        return isManifest_;
      }
      /**
       * <code>optional bool is_manifest = 6 [(.description) = "The object is a manifest, not a chunk"];</code>
       */
      public Builder setIsManifest(boolean value) {
        bitField0_ |= 0x00000020;
        isManifest_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool is_manifest = 6 [(.description) = "The object is a manifest, not a chunk"];</code>
       */
      public Builder clearIsManifest() {
        bitField0_ = (bitField0_ & ~0x00000020);
        isManifest_ = false;
        onChanged();
        return this;
      }

      private long objectSize_ ;
      /**
       * <code>optional uint64 object_size = 7 [(.description) = "object size in bytes"];</code>
       */
      public boolean hasObjectSize() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional uint64 object_size = 7 [(.description) = "object size in bytes"];</code>
       */
      public long getObjectSize() {
        return objectSize_;
      }
      /**
       * <code>optional uint64 object_size = 7 [(.description) = "object size in bytes"];</code>
       */
      public Builder setObjectSize(long value) {
        bitField0_ |= 0x00000040;
        objectSize_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 object_size = 7 [(.description) = "object size in bytes"];</code>
       */
      public Builder clearObjectSize() {
        bitField0_ = (bitField0_ & ~0x00000040);
        objectSize_ = 0L;
        onChanged();
        return this;
      }

      private int corruptionType_ ;
      /**
       * <code>optional uint32 corruption_type = 8 [(.description) = "See EContentCorruptionType"];</code>
       */
      public boolean hasCorruptionType() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional uint32 corruption_type = 8 [(.description) = "See EContentCorruptionType"];</code>
       */
      public int getCorruptionType() {
        return corruptionType_;
      }
      /**
       * <code>optional uint32 corruption_type = 8 [(.description) = "See EContentCorruptionType"];</code>
       */
      public Builder setCorruptionType(int value) {
        bitField0_ |= 0x00000080;
        corruptionType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 corruption_type = 8 [(.description) = "See EContentCorruptionType"];</code>
       */
      public Builder clearCorruptionType() {
        bitField0_ = (bitField0_ & ~0x00000080);
        corruptionType_ = 0;
        onChanged();
        return this;
      }

      private boolean usedHttps_ ;
      /**
       * <code>optional bool used_https = 9 [(.description) = "the request was HTTPS"];</code>
       */
      public boolean hasUsedHttps() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional bool used_https = 9 [(.description) = "the request was HTTPS"];</code>
       */
      public boolean getUsedHttps() {
        return usedHttps_;
      }
      /**
       * <code>optional bool used_https = 9 [(.description) = "the request was HTTPS"];</code>
       */
      public Builder setUsedHttps(boolean value) {
        bitField0_ |= 0x00000100;
        usedHttps_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool used_https = 9 [(.description) = "the request was HTTPS"];</code>
       */
      public Builder clearUsedHttps() {
        bitField0_ = (bitField0_ & ~0x00000100);
        usedHttps_ = false;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:CDataPublisher_ClientContentCorruptionReport_Notification)
    }

    // @@protoc_insertion_point(class_scope:CDataPublisher_ClientContentCorruptionReport_Notification)
    private static final SteammessagesDatapublisherSteamclient.CDataPublisher_ClientContentCorruptionReport_Notification DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new SteammessagesDatapublisherSteamclient.CDataPublisher_ClientContentCorruptionReport_Notification();
    }

    public static SteammessagesDatapublisherSteamclient.CDataPublisher_ClientContentCorruptionReport_Notification getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<CDataPublisher_ClientContentCorruptionReport_Notification>
        PARSER = new com.google.protobuf.AbstractParser<CDataPublisher_ClientContentCorruptionReport_Notification>() {
      public CDataPublisher_ClientContentCorruptionReport_Notification parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new CDataPublisher_ClientContentCorruptionReport_Notification(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CDataPublisher_ClientContentCorruptionReport_Notification> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CDataPublisher_ClientContentCorruptionReport_Notification> getParserForType() {
      return PARSER;
    }

    public SteammessagesDatapublisherSteamclient.CDataPublisher_ClientContentCorruptionReport_Notification getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CDataPublisher_ClientContentCorruptionReport_Notification_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CDataPublisher_ClientContentCorruptionReport_Notification_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n-steammessages_datapublisher.steamclien" +
      "t.proto\032,steammessages_unified_base.stea" +
      "mclient.proto\"\301\003\n9CDataPublisher_ClientC" +
      "ontentCorruptionReport_Notification\022\r\n\005a" +
      "ppid\030\001 \001(\r\022\017\n\007depotid\030\002 \001(\r\0229\n\017download_" +
      "source\030\003 \001(\tB \202\265\030\034host name of download " +
      "source\022.\n\010objectid\030\004 \001(\tB\034\202\265\030\030Chunk SHA " +
      "or Manifest ID\022\"\n\006cellid\030\005 \001(\rB\022\202\265\030\016Clie" +
      "nt Cell ID\022>\n\013is_manifest\030\006 \001(\010B)\202\265\030%The" +
      " object is a manifest, not a chunk\022-\n\013ob",
      "ject_size\030\007 \001(\004B\030\202\265\030\024object size in byte" +
      "s\0227\n\017corruption_type\030\010 \001(\rB\036\202\265\030\032See ECon" +
      "tentCorruptionType\022-\n\nused_https\030\t \001(\010B\031" +
      "\202\265\030\025the request was HTTPS2\242\001\n\rDataPublis" +
      "her\022h\n\035ClientContentCorruptionReport\022:.C" +
      "DataPublisher_ClientContentCorruptionRep" +
      "ort_Notification\032\013.NoResponse\032\'\202\265\030#Data " +
      "Publisher (DP) server servicesB\003\200\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          SteammessagesUnifiedBaseSteamclient.getDescriptor(),
        }, assigner);
    internal_static_CDataPublisher_ClientContentCorruptionReport_Notification_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CDataPublisher_ClientContentCorruptionReport_Notification_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CDataPublisher_ClientContentCorruptionReport_Notification_descriptor,
        new java.lang.String[] { "Appid", "Depotid", "DownloadSource", "Objectid", "Cellid", "IsManifest", "ObjectSize", "CorruptionType", "UsedHttps", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(SteammessagesUnifiedBaseSteamclient.description);
    registry.add(SteammessagesUnifiedBaseSteamclient.serviceDescription);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    SteammessagesUnifiedBaseSteamclient.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
