// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: steammessages_useraccount.steamclient.proto
package com.jsteamkit.internals.proto;

public final class SteammessagesUseraccountSteamclient {
  private SteammessagesUseraccountSteamclient() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CUserAccount_GetAccountLinkStatus_RequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CUserAccount_GetAccountLinkStatus_Request)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code CUserAccount_GetAccountLinkStatus_Request}
   */
  public  static final class CUserAccount_GetAccountLinkStatus_Request extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:CUserAccount_GetAccountLinkStatus_Request)
      CUserAccount_GetAccountLinkStatus_RequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CUserAccount_GetAccountLinkStatus_Request.newBuilder() to construct.
    private CUserAccount_GetAccountLinkStatus_Request(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CUserAccount_GetAccountLinkStatus_Request() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CUserAccount_GetAccountLinkStatus_Request(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SteammessagesUseraccountSteamclient.internal_static_CUserAccount_GetAccountLinkStatus_Request_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SteammessagesUseraccountSteamclient.internal_static_CUserAccount_GetAccountLinkStatus_Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SteammessagesUseraccountSteamclient.CUserAccount_GetAccountLinkStatus_Request.class, SteammessagesUseraccountSteamclient.CUserAccount_GetAccountLinkStatus_Request.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof SteammessagesUseraccountSteamclient.CUserAccount_GetAccountLinkStatus_Request)) {
        return super.equals(obj);
      }
      SteammessagesUseraccountSteamclient.CUserAccount_GetAccountLinkStatus_Request other = (SteammessagesUseraccountSteamclient.CUserAccount_GetAccountLinkStatus_Request) obj;

      boolean result = true;
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static SteammessagesUseraccountSteamclient.CUserAccount_GetAccountLinkStatus_Request parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SteammessagesUseraccountSteamclient.CUserAccount_GetAccountLinkStatus_Request parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SteammessagesUseraccountSteamclient.CUserAccount_GetAccountLinkStatus_Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SteammessagesUseraccountSteamclient.CUserAccount_GetAccountLinkStatus_Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SteammessagesUseraccountSteamclient.CUserAccount_GetAccountLinkStatus_Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SteammessagesUseraccountSteamclient.CUserAccount_GetAccountLinkStatus_Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SteammessagesUseraccountSteamclient.CUserAccount_GetAccountLinkStatus_Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SteammessagesUseraccountSteamclient.CUserAccount_GetAccountLinkStatus_Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static SteammessagesUseraccountSteamclient.CUserAccount_GetAccountLinkStatus_Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static SteammessagesUseraccountSteamclient.CUserAccount_GetAccountLinkStatus_Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static SteammessagesUseraccountSteamclient.CUserAccount_GetAccountLinkStatus_Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SteammessagesUseraccountSteamclient.CUserAccount_GetAccountLinkStatus_Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(SteammessagesUseraccountSteamclient.CUserAccount_GetAccountLinkStatus_Request prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CUserAccount_GetAccountLinkStatus_Request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CUserAccount_GetAccountLinkStatus_Request)
        SteammessagesUseraccountSteamclient.CUserAccount_GetAccountLinkStatus_RequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SteammessagesUseraccountSteamclient.internal_static_CUserAccount_GetAccountLinkStatus_Request_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SteammessagesUseraccountSteamclient.internal_static_CUserAccount_GetAccountLinkStatus_Request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                SteammessagesUseraccountSteamclient.CUserAccount_GetAccountLinkStatus_Request.class, SteammessagesUseraccountSteamclient.CUserAccount_GetAccountLinkStatus_Request.Builder.class);
      }

      // Construct using SteammessagesUseraccountSteamclient.CUserAccount_GetAccountLinkStatus_Request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SteammessagesUseraccountSteamclient.internal_static_CUserAccount_GetAccountLinkStatus_Request_descriptor;
      }

      public SteammessagesUseraccountSteamclient.CUserAccount_GetAccountLinkStatus_Request getDefaultInstanceForType() {
        return SteammessagesUseraccountSteamclient.CUserAccount_GetAccountLinkStatus_Request.getDefaultInstance();
      }

      public SteammessagesUseraccountSteamclient.CUserAccount_GetAccountLinkStatus_Request build() {
        SteammessagesUseraccountSteamclient.CUserAccount_GetAccountLinkStatus_Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public SteammessagesUseraccountSteamclient.CUserAccount_GetAccountLinkStatus_Request buildPartial() {
        SteammessagesUseraccountSteamclient.CUserAccount_GetAccountLinkStatus_Request result = new SteammessagesUseraccountSteamclient.CUserAccount_GetAccountLinkStatus_Request(this);
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof SteammessagesUseraccountSteamclient.CUserAccount_GetAccountLinkStatus_Request) {
          return mergeFrom((SteammessagesUseraccountSteamclient.CUserAccount_GetAccountLinkStatus_Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(SteammessagesUseraccountSteamclient.CUserAccount_GetAccountLinkStatus_Request other) {
        if (other == SteammessagesUseraccountSteamclient.CUserAccount_GetAccountLinkStatus_Request.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        SteammessagesUseraccountSteamclient.CUserAccount_GetAccountLinkStatus_Request parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (SteammessagesUseraccountSteamclient.CUserAccount_GetAccountLinkStatus_Request) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:CUserAccount_GetAccountLinkStatus_Request)
    }

    // @@protoc_insertion_point(class_scope:CUserAccount_GetAccountLinkStatus_Request)
    private static final SteammessagesUseraccountSteamclient.CUserAccount_GetAccountLinkStatus_Request DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new SteammessagesUseraccountSteamclient.CUserAccount_GetAccountLinkStatus_Request();
    }

    public static SteammessagesUseraccountSteamclient.CUserAccount_GetAccountLinkStatus_Request getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<CUserAccount_GetAccountLinkStatus_Request>
        PARSER = new com.google.protobuf.AbstractParser<CUserAccount_GetAccountLinkStatus_Request>() {
      public CUserAccount_GetAccountLinkStatus_Request parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new CUserAccount_GetAccountLinkStatus_Request(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CUserAccount_GetAccountLinkStatus_Request> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CUserAccount_GetAccountLinkStatus_Request> getParserForType() {
      return PARSER;
    }

    public SteammessagesUseraccountSteamclient.CUserAccount_GetAccountLinkStatus_Request getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CUserAccount_GetAccountLinkStatus_ResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CUserAccount_GetAccountLinkStatus_Response)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional uint32 pwid = 1;</code>
     */
    boolean hasPwid();
    /**
     * <code>optional uint32 pwid = 1;</code>
     */
    int getPwid();

    /**
     * <code>optional uint32 identity_verification = 2;</code>
     */
    boolean hasIdentityVerification();
    /**
     * <code>optional uint32 identity_verification = 2;</code>
     */
    int getIdentityVerification();
  }
  /**
   * Protobuf type {@code CUserAccount_GetAccountLinkStatus_Response}
   */
  public  static final class CUserAccount_GetAccountLinkStatus_Response extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:CUserAccount_GetAccountLinkStatus_Response)
      CUserAccount_GetAccountLinkStatus_ResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CUserAccount_GetAccountLinkStatus_Response.newBuilder() to construct.
    private CUserAccount_GetAccountLinkStatus_Response(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CUserAccount_GetAccountLinkStatus_Response() {
      pwid_ = 0;
      identityVerification_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CUserAccount_GetAccountLinkStatus_Response(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              pwid_ = input.readUInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              identityVerification_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SteammessagesUseraccountSteamclient.internal_static_CUserAccount_GetAccountLinkStatus_Response_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SteammessagesUseraccountSteamclient.internal_static_CUserAccount_GetAccountLinkStatus_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SteammessagesUseraccountSteamclient.CUserAccount_GetAccountLinkStatus_Response.class, SteammessagesUseraccountSteamclient.CUserAccount_GetAccountLinkStatus_Response.Builder.class);
    }

    private int bitField0_;
    public static final int PWID_FIELD_NUMBER = 1;
    private int pwid_;
    /**
     * <code>optional uint32 pwid = 1;</code>
     */
    public boolean hasPwid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional uint32 pwid = 1;</code>
     */
    public int getPwid() {
      return pwid_;
    }

    public static final int IDENTITY_VERIFICATION_FIELD_NUMBER = 2;
    private int identityVerification_;
    /**
     * <code>optional uint32 identity_verification = 2;</code>
     */
    public boolean hasIdentityVerification() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional uint32 identity_verification = 2;</code>
     */
    public int getIdentityVerification() {
      return identityVerification_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, pwid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, identityVerification_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, pwid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, identityVerification_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof SteammessagesUseraccountSteamclient.CUserAccount_GetAccountLinkStatus_Response)) {
        return super.equals(obj);
      }
      SteammessagesUseraccountSteamclient.CUserAccount_GetAccountLinkStatus_Response other = (SteammessagesUseraccountSteamclient.CUserAccount_GetAccountLinkStatus_Response) obj;

      boolean result = true;
      result = result && (hasPwid() == other.hasPwid());
      if (hasPwid()) {
        result = result && (getPwid()
            == other.getPwid());
      }
      result = result && (hasIdentityVerification() == other.hasIdentityVerification());
      if (hasIdentityVerification()) {
        result = result && (getIdentityVerification()
            == other.getIdentityVerification());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasPwid()) {
        hash = (37 * hash) + PWID_FIELD_NUMBER;
        hash = (53 * hash) + getPwid();
      }
      if (hasIdentityVerification()) {
        hash = (37 * hash) + IDENTITY_VERIFICATION_FIELD_NUMBER;
        hash = (53 * hash) + getIdentityVerification();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static SteammessagesUseraccountSteamclient.CUserAccount_GetAccountLinkStatus_Response parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SteammessagesUseraccountSteamclient.CUserAccount_GetAccountLinkStatus_Response parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SteammessagesUseraccountSteamclient.CUserAccount_GetAccountLinkStatus_Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SteammessagesUseraccountSteamclient.CUserAccount_GetAccountLinkStatus_Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SteammessagesUseraccountSteamclient.CUserAccount_GetAccountLinkStatus_Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SteammessagesUseraccountSteamclient.CUserAccount_GetAccountLinkStatus_Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SteammessagesUseraccountSteamclient.CUserAccount_GetAccountLinkStatus_Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SteammessagesUseraccountSteamclient.CUserAccount_GetAccountLinkStatus_Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static SteammessagesUseraccountSteamclient.CUserAccount_GetAccountLinkStatus_Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static SteammessagesUseraccountSteamclient.CUserAccount_GetAccountLinkStatus_Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static SteammessagesUseraccountSteamclient.CUserAccount_GetAccountLinkStatus_Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SteammessagesUseraccountSteamclient.CUserAccount_GetAccountLinkStatus_Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(SteammessagesUseraccountSteamclient.CUserAccount_GetAccountLinkStatus_Response prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CUserAccount_GetAccountLinkStatus_Response}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CUserAccount_GetAccountLinkStatus_Response)
        SteammessagesUseraccountSteamclient.CUserAccount_GetAccountLinkStatus_ResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SteammessagesUseraccountSteamclient.internal_static_CUserAccount_GetAccountLinkStatus_Response_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SteammessagesUseraccountSteamclient.internal_static_CUserAccount_GetAccountLinkStatus_Response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                SteammessagesUseraccountSteamclient.CUserAccount_GetAccountLinkStatus_Response.class, SteammessagesUseraccountSteamclient.CUserAccount_GetAccountLinkStatus_Response.Builder.class);
      }

      // Construct using SteammessagesUseraccountSteamclient.CUserAccount_GetAccountLinkStatus_Response.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        pwid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        identityVerification_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SteammessagesUseraccountSteamclient.internal_static_CUserAccount_GetAccountLinkStatus_Response_descriptor;
      }

      public SteammessagesUseraccountSteamclient.CUserAccount_GetAccountLinkStatus_Response getDefaultInstanceForType() {
        return SteammessagesUseraccountSteamclient.CUserAccount_GetAccountLinkStatus_Response.getDefaultInstance();
      }

      public SteammessagesUseraccountSteamclient.CUserAccount_GetAccountLinkStatus_Response build() {
        SteammessagesUseraccountSteamclient.CUserAccount_GetAccountLinkStatus_Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public SteammessagesUseraccountSteamclient.CUserAccount_GetAccountLinkStatus_Response buildPartial() {
        SteammessagesUseraccountSteamclient.CUserAccount_GetAccountLinkStatus_Response result = new SteammessagesUseraccountSteamclient.CUserAccount_GetAccountLinkStatus_Response(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.pwid_ = pwid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.identityVerification_ = identityVerification_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof SteammessagesUseraccountSteamclient.CUserAccount_GetAccountLinkStatus_Response) {
          return mergeFrom((SteammessagesUseraccountSteamclient.CUserAccount_GetAccountLinkStatus_Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(SteammessagesUseraccountSteamclient.CUserAccount_GetAccountLinkStatus_Response other) {
        if (other == SteammessagesUseraccountSteamclient.CUserAccount_GetAccountLinkStatus_Response.getDefaultInstance()) return this;
        if (other.hasPwid()) {
          setPwid(other.getPwid());
        }
        if (other.hasIdentityVerification()) {
          setIdentityVerification(other.getIdentityVerification());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        SteammessagesUseraccountSteamclient.CUserAccount_GetAccountLinkStatus_Response parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (SteammessagesUseraccountSteamclient.CUserAccount_GetAccountLinkStatus_Response) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int pwid_ ;
      /**
       * <code>optional uint32 pwid = 1;</code>
       */
      public boolean hasPwid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional uint32 pwid = 1;</code>
       */
      public int getPwid() {
        return pwid_;
      }
      /**
       * <code>optional uint32 pwid = 1;</code>
       */
      public Builder setPwid(int value) {
        bitField0_ |= 0x00000001;
        pwid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 pwid = 1;</code>
       */
      public Builder clearPwid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        pwid_ = 0;
        onChanged();
        return this;
      }

      private int identityVerification_ ;
      /**
       * <code>optional uint32 identity_verification = 2;</code>
       */
      public boolean hasIdentityVerification() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional uint32 identity_verification = 2;</code>
       */
      public int getIdentityVerification() {
        return identityVerification_;
      }
      /**
       * <code>optional uint32 identity_verification = 2;</code>
       */
      public Builder setIdentityVerification(int value) {
        bitField0_ |= 0x00000002;
        identityVerification_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 identity_verification = 2;</code>
       */
      public Builder clearIdentityVerification() {
        bitField0_ = (bitField0_ & ~0x00000002);
        identityVerification_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:CUserAccount_GetAccountLinkStatus_Response)
    }

    // @@protoc_insertion_point(class_scope:CUserAccount_GetAccountLinkStatus_Response)
    private static final SteammessagesUseraccountSteamclient.CUserAccount_GetAccountLinkStatus_Response DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new SteammessagesUseraccountSteamclient.CUserAccount_GetAccountLinkStatus_Response();
    }

    public static SteammessagesUseraccountSteamclient.CUserAccount_GetAccountLinkStatus_Response getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<CUserAccount_GetAccountLinkStatus_Response>
        PARSER = new com.google.protobuf.AbstractParser<CUserAccount_GetAccountLinkStatus_Response>() {
      public CUserAccount_GetAccountLinkStatus_Response parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new CUserAccount_GetAccountLinkStatus_Response(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CUserAccount_GetAccountLinkStatus_Response> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CUserAccount_GetAccountLinkStatus_Response> getParserForType() {
      return PARSER;
    }

    public SteammessagesUseraccountSteamclient.CUserAccount_GetAccountLinkStatus_Response getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CUserAccount_GetAccountLinkStatus_Request_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CUserAccount_GetAccountLinkStatus_Request_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CUserAccount_GetAccountLinkStatus_Response_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CUserAccount_GetAccountLinkStatus_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n+steammessages_useraccount.steamclient." +
      "proto\032,steammessages_unified_base.steamc" +
      "lient.proto\"+\n)CUserAccount_GetAccountLi" +
      "nkStatus_Request\"Y\n*CUserAccount_GetAcco" +
      "untLinkStatus_Response\022\014\n\004pwid\030\001 \001(\r\022\035\n\025" +
      "identity_verification\030\002 \001(\r2\317\001\n\013UserAcco" +
      "unt\022\220\001\n\024GetAccountLinkStatus\022*.CUserAcco" +
      "unt_GetAccountLinkStatus_Request\032+.CUser" +
      "Account_GetAccountLinkStatus_Response\"\037\202" +
      "\265\030\033Fetches account link status\032-\202\265\030)A se",
      "rvice to get user account informationB\003\200" +
      "\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          SteammessagesUnifiedBaseSteamclient.getDescriptor(),
        }, assigner);
    internal_static_CUserAccount_GetAccountLinkStatus_Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CUserAccount_GetAccountLinkStatus_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CUserAccount_GetAccountLinkStatus_Request_descriptor,
        new java.lang.String[] { });
    internal_static_CUserAccount_GetAccountLinkStatus_Response_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_CUserAccount_GetAccountLinkStatus_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CUserAccount_GetAccountLinkStatus_Response_descriptor,
        new java.lang.String[] { "Pwid", "IdentityVerification", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(SteammessagesUnifiedBaseSteamclient.methodDescription);
    registry.add(SteammessagesUnifiedBaseSteamclient.serviceDescription);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    SteammessagesUnifiedBaseSteamclient.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
