// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: steammessages_secrets.steamclient.proto

package com.jsteamkit.internals.proto;

public final class SteammessagesSecretsSteamclient {
  private SteammessagesSecretsSteamclient() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code EKeyEscrowUsage}
   */
  public enum EKeyEscrowUsage
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>k_EKeyEscrowUsageStreamingDevice = 0;</code>
     */
    k_EKeyEscrowUsageStreamingDevice(0, 0),
    ;

    /**
     * <code>k_EKeyEscrowUsageStreamingDevice = 0;</code>
     */
    public static final int k_EKeyEscrowUsageStreamingDevice_VALUE = 0;


    public final int getNumber() { return value; }

    public static EKeyEscrowUsage valueOf(int value) {
      switch (value) {
        case 0: return k_EKeyEscrowUsageStreamingDevice;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<EKeyEscrowUsage>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<EKeyEscrowUsage>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<EKeyEscrowUsage>() {
            public EKeyEscrowUsage findValueByNumber(int number) {
              return EKeyEscrowUsage.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return SteammessagesSecretsSteamclient.getDescriptor().getEnumTypes().get(0);
    }

    private static final EKeyEscrowUsage[] VALUES = values();

    public static EKeyEscrowUsage valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private EKeyEscrowUsage(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:EKeyEscrowUsage)
  }

  public interface CKeyEscrow_RequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CKeyEscrow_Request)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bytes rsa_oaep_sha_ticket = 1;</code>
     */
    boolean hasRsaOaepShaTicket();
    /**
     * <code>optional bytes rsa_oaep_sha_ticket = 1;</code>
     */
    com.google.protobuf.ByteString getRsaOaepShaTicket();

    /**
     * <code>optional bytes password = 2;</code>
     */
    boolean hasPassword();
    /**
     * <code>optional bytes password = 2;</code>
     */
    com.google.protobuf.ByteString getPassword();

    /**
     * <code>optional .EKeyEscrowUsage usage = 3 [default = k_EKeyEscrowUsageStreamingDevice];</code>
     */
    boolean hasUsage();
    /**
     * <code>optional .EKeyEscrowUsage usage = 3 [default = k_EKeyEscrowUsageStreamingDevice];</code>
     */
    SteammessagesSecretsSteamclient.EKeyEscrowUsage getUsage();

    /**
     * <code>optional string device_name = 4;</code>
     */
    boolean hasDeviceName();
    /**
     * <code>optional string device_name = 4;</code>
     */
    java.lang.String getDeviceName();
    /**
     * <code>optional string device_name = 4;</code>
     */
    com.google.protobuf.ByteString
        getDeviceNameBytes();
  }
  /**
   * Protobuf type {@code CKeyEscrow_Request}
   */
  public static final class CKeyEscrow_Request extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:CKeyEscrow_Request)
      CKeyEscrow_RequestOrBuilder {
    // Use CKeyEscrow_Request.newBuilder() to construct.
    private CKeyEscrow_Request(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CKeyEscrow_Request(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CKeyEscrow_Request defaultInstance;
    public static CKeyEscrow_Request getDefaultInstance() {
      return defaultInstance;
    }

    public CKeyEscrow_Request getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CKeyEscrow_Request(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              rsaOaepShaTicket_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              password_ = input.readBytes();
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
              SteammessagesSecretsSteamclient.EKeyEscrowUsage value = SteammessagesSecretsSteamclient.EKeyEscrowUsage.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(3, rawValue);
              } else {
                bitField0_ |= 0x00000004;
                usage_ = value;
              }
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              deviceName_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SteammessagesSecretsSteamclient.internal_static_CKeyEscrow_Request_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SteammessagesSecretsSteamclient.internal_static_CKeyEscrow_Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SteammessagesSecretsSteamclient.CKeyEscrow_Request.class, SteammessagesSecretsSteamclient.CKeyEscrow_Request.Builder.class);
    }

    public static com.google.protobuf.Parser<CKeyEscrow_Request> PARSER =
        new com.google.protobuf.AbstractParser<CKeyEscrow_Request>() {
      public CKeyEscrow_Request parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CKeyEscrow_Request(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CKeyEscrow_Request> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int RSA_OAEP_SHA_TICKET_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString rsaOaepShaTicket_;
    /**
     * <code>optional bytes rsa_oaep_sha_ticket = 1;</code>
     */
    public boolean hasRsaOaepShaTicket() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional bytes rsa_oaep_sha_ticket = 1;</code>
     */
    public com.google.protobuf.ByteString getRsaOaepShaTicket() {
      return rsaOaepShaTicket_;
    }

    public static final int PASSWORD_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString password_;
    /**
     * <code>optional bytes password = 2;</code>
     */
    public boolean hasPassword() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bytes password = 2;</code>
     */
    public com.google.protobuf.ByteString getPassword() {
      return password_;
    }

    public static final int USAGE_FIELD_NUMBER = 3;
    private SteammessagesSecretsSteamclient.EKeyEscrowUsage usage_;
    /**
     * <code>optional .EKeyEscrowUsage usage = 3 [default = k_EKeyEscrowUsageStreamingDevice];</code>
     */
    public boolean hasUsage() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .EKeyEscrowUsage usage = 3 [default = k_EKeyEscrowUsageStreamingDevice];</code>
     */
    public SteammessagesSecretsSteamclient.EKeyEscrowUsage getUsage() {
      return usage_;
    }

    public static final int DEVICE_NAME_FIELD_NUMBER = 4;
    private java.lang.Object deviceName_;
    /**
     * <code>optional string device_name = 4;</code>
     */
    public boolean hasDeviceName() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string device_name = 4;</code>
     */
    public java.lang.String getDeviceName() {
      java.lang.Object ref = deviceName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          deviceName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string device_name = 4;</code>
     */
    public com.google.protobuf.ByteString
        getDeviceNameBytes() {
      java.lang.Object ref = deviceName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      rsaOaepShaTicket_ = com.google.protobuf.ByteString.EMPTY;
      password_ = com.google.protobuf.ByteString.EMPTY;
      usage_ = SteammessagesSecretsSteamclient.EKeyEscrowUsage.k_EKeyEscrowUsageStreamingDevice;
      deviceName_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, rsaOaepShaTicket_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, password_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeEnum(3, usage_.getNumber());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getDeviceNameBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, rsaOaepShaTicket_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, password_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, usage_.getNumber());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getDeviceNameBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static SteammessagesSecretsSteamclient.CKeyEscrow_Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SteammessagesSecretsSteamclient.CKeyEscrow_Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SteammessagesSecretsSteamclient.CKeyEscrow_Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SteammessagesSecretsSteamclient.CKeyEscrow_Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SteammessagesSecretsSteamclient.CKeyEscrow_Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static SteammessagesSecretsSteamclient.CKeyEscrow_Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static SteammessagesSecretsSteamclient.CKeyEscrow_Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static SteammessagesSecretsSteamclient.CKeyEscrow_Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static SteammessagesSecretsSteamclient.CKeyEscrow_Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static SteammessagesSecretsSteamclient.CKeyEscrow_Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(SteammessagesSecretsSteamclient.CKeyEscrow_Request prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CKeyEscrow_Request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CKeyEscrow_Request)
        SteammessagesSecretsSteamclient.CKeyEscrow_RequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SteammessagesSecretsSteamclient.internal_static_CKeyEscrow_Request_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SteammessagesSecretsSteamclient.internal_static_CKeyEscrow_Request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                SteammessagesSecretsSteamclient.CKeyEscrow_Request.class, SteammessagesSecretsSteamclient.CKeyEscrow_Request.Builder.class);
      }

      // Construct using SteammessagesSecretsSteamclient.CKeyEscrow_Request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        rsaOaepShaTicket_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        password_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        usage_ = SteammessagesSecretsSteamclient.EKeyEscrowUsage.k_EKeyEscrowUsageStreamingDevice;
        bitField0_ = (bitField0_ & ~0x00000004);
        deviceName_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SteammessagesSecretsSteamclient.internal_static_CKeyEscrow_Request_descriptor;
      }

      public SteammessagesSecretsSteamclient.CKeyEscrow_Request getDefaultInstanceForType() {
        return SteammessagesSecretsSteamclient.CKeyEscrow_Request.getDefaultInstance();
      }

      public SteammessagesSecretsSteamclient.CKeyEscrow_Request build() {
        SteammessagesSecretsSteamclient.CKeyEscrow_Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public SteammessagesSecretsSteamclient.CKeyEscrow_Request buildPartial() {
        SteammessagesSecretsSteamclient.CKeyEscrow_Request result = new SteammessagesSecretsSteamclient.CKeyEscrow_Request(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.rsaOaepShaTicket_ = rsaOaepShaTicket_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.password_ = password_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.usage_ = usage_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.deviceName_ = deviceName_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof SteammessagesSecretsSteamclient.CKeyEscrow_Request) {
          return mergeFrom((SteammessagesSecretsSteamclient.CKeyEscrow_Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(SteammessagesSecretsSteamclient.CKeyEscrow_Request other) {
        if (other == SteammessagesSecretsSteamclient.CKeyEscrow_Request.getDefaultInstance()) return this;
        if (other.hasRsaOaepShaTicket()) {
          setRsaOaepShaTicket(other.getRsaOaepShaTicket());
        }
        if (other.hasPassword()) {
          setPassword(other.getPassword());
        }
        if (other.hasUsage()) {
          setUsage(other.getUsage());
        }
        if (other.hasDeviceName()) {
          bitField0_ |= 0x00000008;
          deviceName_ = other.deviceName_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        SteammessagesSecretsSteamclient.CKeyEscrow_Request parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (SteammessagesSecretsSteamclient.CKeyEscrow_Request) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString rsaOaepShaTicket_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes rsa_oaep_sha_ticket = 1;</code>
       */
      public boolean hasRsaOaepShaTicket() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional bytes rsa_oaep_sha_ticket = 1;</code>
       */
      public com.google.protobuf.ByteString getRsaOaepShaTicket() {
        return rsaOaepShaTicket_;
      }
      /**
       * <code>optional bytes rsa_oaep_sha_ticket = 1;</code>
       */
      public Builder setRsaOaepShaTicket(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        rsaOaepShaTicket_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes rsa_oaep_sha_ticket = 1;</code>
       */
      public Builder clearRsaOaepShaTicket() {
        bitField0_ = (bitField0_ & ~0x00000001);
        rsaOaepShaTicket_ = getDefaultInstance().getRsaOaepShaTicket();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString password_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes password = 2;</code>
       */
      public boolean hasPassword() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional bytes password = 2;</code>
       */
      public com.google.protobuf.ByteString getPassword() {
        return password_;
      }
      /**
       * <code>optional bytes password = 2;</code>
       */
      public Builder setPassword(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        password_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes password = 2;</code>
       */
      public Builder clearPassword() {
        bitField0_ = (bitField0_ & ~0x00000002);
        password_ = getDefaultInstance().getPassword();
        onChanged();
        return this;
      }

      private SteammessagesSecretsSteamclient.EKeyEscrowUsage usage_ = SteammessagesSecretsSteamclient.EKeyEscrowUsage.k_EKeyEscrowUsageStreamingDevice;
      /**
       * <code>optional .EKeyEscrowUsage usage = 3 [default = k_EKeyEscrowUsageStreamingDevice];</code>
       */
      public boolean hasUsage() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .EKeyEscrowUsage usage = 3 [default = k_EKeyEscrowUsageStreamingDevice];</code>
       */
      public SteammessagesSecretsSteamclient.EKeyEscrowUsage getUsage() {
        return usage_;
      }
      /**
       * <code>optional .EKeyEscrowUsage usage = 3 [default = k_EKeyEscrowUsageStreamingDevice];</code>
       */
      public Builder setUsage(SteammessagesSecretsSteamclient.EKeyEscrowUsage value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        usage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .EKeyEscrowUsage usage = 3 [default = k_EKeyEscrowUsageStreamingDevice];</code>
       */
      public Builder clearUsage() {
        bitField0_ = (bitField0_ & ~0x00000004);
        usage_ = SteammessagesSecretsSteamclient.EKeyEscrowUsage.k_EKeyEscrowUsageStreamingDevice;
        onChanged();
        return this;
      }

      private java.lang.Object deviceName_ = "";
      /**
       * <code>optional string device_name = 4;</code>
       */
      public boolean hasDeviceName() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string device_name = 4;</code>
       */
      public java.lang.String getDeviceName() {
        java.lang.Object ref = deviceName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            deviceName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string device_name = 4;</code>
       */
      public com.google.protobuf.ByteString
          getDeviceNameBytes() {
        java.lang.Object ref = deviceName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          deviceName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string device_name = 4;</code>
       */
      public Builder setDeviceName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        deviceName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string device_name = 4;</code>
       */
      public Builder clearDeviceName() {
        bitField0_ = (bitField0_ & ~0x00000008);
        deviceName_ = getDefaultInstance().getDeviceName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string device_name = 4;</code>
       */
      public Builder setDeviceNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        deviceName_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:CKeyEscrow_Request)
    }

    static {
      defaultInstance = new CKeyEscrow_Request(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:CKeyEscrow_Request)
  }

  public interface CKeyEscrow_TicketOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CKeyEscrow_Ticket)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bytes password = 1;</code>
     */
    boolean hasPassword();
    /**
     * <code>optional bytes password = 1;</code>
     */
    com.google.protobuf.ByteString getPassword();

    /**
     * <code>optional uint64 identifier = 2;</code>
     */
    boolean hasIdentifier();
    /**
     * <code>optional uint64 identifier = 2;</code>
     */
    long getIdentifier();

    /**
     * <code>optional bytes payload = 3;</code>
     */
    boolean hasPayload();
    /**
     * <code>optional bytes payload = 3;</code>
     */
    com.google.protobuf.ByteString getPayload();

    /**
     * <code>optional uint32 timestamp = 4;</code>
     */
    boolean hasTimestamp();
    /**
     * <code>optional uint32 timestamp = 4;</code>
     */
    int getTimestamp();

    /**
     * <code>optional .EKeyEscrowUsage usage = 5 [default = k_EKeyEscrowUsageStreamingDevice];</code>
     */
    boolean hasUsage();
    /**
     * <code>optional .EKeyEscrowUsage usage = 5 [default = k_EKeyEscrowUsageStreamingDevice];</code>
     */
    SteammessagesSecretsSteamclient.EKeyEscrowUsage getUsage();

    /**
     * <code>optional string device_name = 6;</code>
     */
    boolean hasDeviceName();
    /**
     * <code>optional string device_name = 6;</code>
     */
    java.lang.String getDeviceName();
    /**
     * <code>optional string device_name = 6;</code>
     */
    com.google.protobuf.ByteString
        getDeviceNameBytes();

    /**
     * <code>optional string device_model = 7;</code>
     */
    boolean hasDeviceModel();
    /**
     * <code>optional string device_model = 7;</code>
     */
    java.lang.String getDeviceModel();
    /**
     * <code>optional string device_model = 7;</code>
     */
    com.google.protobuf.ByteString
        getDeviceModelBytes();

    /**
     * <code>optional string device_serial = 8;</code>
     */
    boolean hasDeviceSerial();
    /**
     * <code>optional string device_serial = 8;</code>
     */
    java.lang.String getDeviceSerial();
    /**
     * <code>optional string device_serial = 8;</code>
     */
    com.google.protobuf.ByteString
        getDeviceSerialBytes();

    /**
     * <code>optional uint32 device_provisioning_id = 9;</code>
     */
    boolean hasDeviceProvisioningId();
    /**
     * <code>optional uint32 device_provisioning_id = 9;</code>
     */
    int getDeviceProvisioningId();
  }
  /**
   * Protobuf type {@code CKeyEscrow_Ticket}
   */
  public static final class CKeyEscrow_Ticket extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:CKeyEscrow_Ticket)
      CKeyEscrow_TicketOrBuilder {
    // Use CKeyEscrow_Ticket.newBuilder() to construct.
    private CKeyEscrow_Ticket(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CKeyEscrow_Ticket(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CKeyEscrow_Ticket defaultInstance;
    public static CKeyEscrow_Ticket getDefaultInstance() {
      return defaultInstance;
    }

    public CKeyEscrow_Ticket getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CKeyEscrow_Ticket(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              password_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              identifier_ = input.readUInt64();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              payload_ = input.readBytes();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              timestamp_ = input.readUInt32();
              break;
            }
            case 40: {
              int rawValue = input.readEnum();
              SteammessagesSecretsSteamclient.EKeyEscrowUsage value = SteammessagesSecretsSteamclient.EKeyEscrowUsage.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(5, rawValue);
              } else {
                bitField0_ |= 0x00000010;
                usage_ = value;
              }
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              deviceName_ = bs;
              break;
            }
            case 58: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000040;
              deviceModel_ = bs;
              break;
            }
            case 66: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000080;
              deviceSerial_ = bs;
              break;
            }
            case 72: {
              bitField0_ |= 0x00000100;
              deviceProvisioningId_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SteammessagesSecretsSteamclient.internal_static_CKeyEscrow_Ticket_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SteammessagesSecretsSteamclient.internal_static_CKeyEscrow_Ticket_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SteammessagesSecretsSteamclient.CKeyEscrow_Ticket.class, SteammessagesSecretsSteamclient.CKeyEscrow_Ticket.Builder.class);
    }

    public static com.google.protobuf.Parser<CKeyEscrow_Ticket> PARSER =
        new com.google.protobuf.AbstractParser<CKeyEscrow_Ticket>() {
      public CKeyEscrow_Ticket parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CKeyEscrow_Ticket(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CKeyEscrow_Ticket> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int PASSWORD_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString password_;
    /**
     * <code>optional bytes password = 1;</code>
     */
    public boolean hasPassword() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional bytes password = 1;</code>
     */
    public com.google.protobuf.ByteString getPassword() {
      return password_;
    }

    public static final int IDENTIFIER_FIELD_NUMBER = 2;
    private long identifier_;
    /**
     * <code>optional uint64 identifier = 2;</code>
     */
    public boolean hasIdentifier() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional uint64 identifier = 2;</code>
     */
    public long getIdentifier() {
      return identifier_;
    }

    public static final int PAYLOAD_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString payload_;
    /**
     * <code>optional bytes payload = 3;</code>
     */
    public boolean hasPayload() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional bytes payload = 3;</code>
     */
    public com.google.protobuf.ByteString getPayload() {
      return payload_;
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 4;
    private int timestamp_;
    /**
     * <code>optional uint32 timestamp = 4;</code>
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional uint32 timestamp = 4;</code>
     */
    public int getTimestamp() {
      return timestamp_;
    }

    public static final int USAGE_FIELD_NUMBER = 5;
    private SteammessagesSecretsSteamclient.EKeyEscrowUsage usage_;
    /**
     * <code>optional .EKeyEscrowUsage usage = 5 [default = k_EKeyEscrowUsageStreamingDevice];</code>
     */
    public boolean hasUsage() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional .EKeyEscrowUsage usage = 5 [default = k_EKeyEscrowUsageStreamingDevice];</code>
     */
    public SteammessagesSecretsSteamclient.EKeyEscrowUsage getUsage() {
      return usage_;
    }

    public static final int DEVICE_NAME_FIELD_NUMBER = 6;
    private java.lang.Object deviceName_;
    /**
     * <code>optional string device_name = 6;</code>
     */
    public boolean hasDeviceName() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string device_name = 6;</code>
     */
    public java.lang.String getDeviceName() {
      java.lang.Object ref = deviceName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          deviceName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string device_name = 6;</code>
     */
    public com.google.protobuf.ByteString
        getDeviceNameBytes() {
      java.lang.Object ref = deviceName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DEVICE_MODEL_FIELD_NUMBER = 7;
    private java.lang.Object deviceModel_;
    /**
     * <code>optional string device_model = 7;</code>
     */
    public boolean hasDeviceModel() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional string device_model = 7;</code>
     */
    public java.lang.String getDeviceModel() {
      java.lang.Object ref = deviceModel_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          deviceModel_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string device_model = 7;</code>
     */
    public com.google.protobuf.ByteString
        getDeviceModelBytes() {
      java.lang.Object ref = deviceModel_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceModel_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DEVICE_SERIAL_FIELD_NUMBER = 8;
    private java.lang.Object deviceSerial_;
    /**
     * <code>optional string device_serial = 8;</code>
     */
    public boolean hasDeviceSerial() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional string device_serial = 8;</code>
     */
    public java.lang.String getDeviceSerial() {
      java.lang.Object ref = deviceSerial_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          deviceSerial_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string device_serial = 8;</code>
     */
    public com.google.protobuf.ByteString
        getDeviceSerialBytes() {
      java.lang.Object ref = deviceSerial_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceSerial_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DEVICE_PROVISIONING_ID_FIELD_NUMBER = 9;
    private int deviceProvisioningId_;
    /**
     * <code>optional uint32 device_provisioning_id = 9;</code>
     */
    public boolean hasDeviceProvisioningId() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional uint32 device_provisioning_id = 9;</code>
     */
    public int getDeviceProvisioningId() {
      return deviceProvisioningId_;
    }

    private void initFields() {
      password_ = com.google.protobuf.ByteString.EMPTY;
      identifier_ = 0L;
      payload_ = com.google.protobuf.ByteString.EMPTY;
      timestamp_ = 0;
      usage_ = SteammessagesSecretsSteamclient.EKeyEscrowUsage.k_EKeyEscrowUsageStreamingDevice;
      deviceName_ = "";
      deviceModel_ = "";
      deviceSerial_ = "";
      deviceProvisioningId_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, password_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt64(2, identifier_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, payload_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeUInt32(4, timestamp_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeEnum(5, usage_.getNumber());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getDeviceNameBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getDeviceModelBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(8, getDeviceSerialBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeUInt32(9, deviceProvisioningId_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, password_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, identifier_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, payload_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, timestamp_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, usage_.getNumber());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getDeviceNameBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getDeviceModelBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, getDeviceSerialBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(9, deviceProvisioningId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static SteammessagesSecretsSteamclient.CKeyEscrow_Ticket parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SteammessagesSecretsSteamclient.CKeyEscrow_Ticket parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SteammessagesSecretsSteamclient.CKeyEscrow_Ticket parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SteammessagesSecretsSteamclient.CKeyEscrow_Ticket parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SteammessagesSecretsSteamclient.CKeyEscrow_Ticket parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static SteammessagesSecretsSteamclient.CKeyEscrow_Ticket parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static SteammessagesSecretsSteamclient.CKeyEscrow_Ticket parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static SteammessagesSecretsSteamclient.CKeyEscrow_Ticket parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static SteammessagesSecretsSteamclient.CKeyEscrow_Ticket parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static SteammessagesSecretsSteamclient.CKeyEscrow_Ticket parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(SteammessagesSecretsSteamclient.CKeyEscrow_Ticket prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CKeyEscrow_Ticket}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CKeyEscrow_Ticket)
        SteammessagesSecretsSteamclient.CKeyEscrow_TicketOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SteammessagesSecretsSteamclient.internal_static_CKeyEscrow_Ticket_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SteammessagesSecretsSteamclient.internal_static_CKeyEscrow_Ticket_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                SteammessagesSecretsSteamclient.CKeyEscrow_Ticket.class, SteammessagesSecretsSteamclient.CKeyEscrow_Ticket.Builder.class);
      }

      // Construct using SteammessagesSecretsSteamclient.CKeyEscrow_Ticket.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        password_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        identifier_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        payload_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        timestamp_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        usage_ = SteammessagesSecretsSteamclient.EKeyEscrowUsage.k_EKeyEscrowUsageStreamingDevice;
        bitField0_ = (bitField0_ & ~0x00000010);
        deviceName_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        deviceModel_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        deviceSerial_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        deviceProvisioningId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000100);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SteammessagesSecretsSteamclient.internal_static_CKeyEscrow_Ticket_descriptor;
      }

      public SteammessagesSecretsSteamclient.CKeyEscrow_Ticket getDefaultInstanceForType() {
        return SteammessagesSecretsSteamclient.CKeyEscrow_Ticket.getDefaultInstance();
      }

      public SteammessagesSecretsSteamclient.CKeyEscrow_Ticket build() {
        SteammessagesSecretsSteamclient.CKeyEscrow_Ticket result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public SteammessagesSecretsSteamclient.CKeyEscrow_Ticket buildPartial() {
        SteammessagesSecretsSteamclient.CKeyEscrow_Ticket result = new SteammessagesSecretsSteamclient.CKeyEscrow_Ticket(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.password_ = password_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.identifier_ = identifier_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.payload_ = payload_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.timestamp_ = timestamp_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.usage_ = usage_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.deviceName_ = deviceName_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.deviceModel_ = deviceModel_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.deviceSerial_ = deviceSerial_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.deviceProvisioningId_ = deviceProvisioningId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof SteammessagesSecretsSteamclient.CKeyEscrow_Ticket) {
          return mergeFrom((SteammessagesSecretsSteamclient.CKeyEscrow_Ticket)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(SteammessagesSecretsSteamclient.CKeyEscrow_Ticket other) {
        if (other == SteammessagesSecretsSteamclient.CKeyEscrow_Ticket.getDefaultInstance()) return this;
        if (other.hasPassword()) {
          setPassword(other.getPassword());
        }
        if (other.hasIdentifier()) {
          setIdentifier(other.getIdentifier());
        }
        if (other.hasPayload()) {
          setPayload(other.getPayload());
        }
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        if (other.hasUsage()) {
          setUsage(other.getUsage());
        }
        if (other.hasDeviceName()) {
          bitField0_ |= 0x00000020;
          deviceName_ = other.deviceName_;
          onChanged();
        }
        if (other.hasDeviceModel()) {
          bitField0_ |= 0x00000040;
          deviceModel_ = other.deviceModel_;
          onChanged();
        }
        if (other.hasDeviceSerial()) {
          bitField0_ |= 0x00000080;
          deviceSerial_ = other.deviceSerial_;
          onChanged();
        }
        if (other.hasDeviceProvisioningId()) {
          setDeviceProvisioningId(other.getDeviceProvisioningId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        SteammessagesSecretsSteamclient.CKeyEscrow_Ticket parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (SteammessagesSecretsSteamclient.CKeyEscrow_Ticket) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString password_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes password = 1;</code>
       */
      public boolean hasPassword() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional bytes password = 1;</code>
       */
      public com.google.protobuf.ByteString getPassword() {
        return password_;
      }
      /**
       * <code>optional bytes password = 1;</code>
       */
      public Builder setPassword(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        password_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes password = 1;</code>
       */
      public Builder clearPassword() {
        bitField0_ = (bitField0_ & ~0x00000001);
        password_ = getDefaultInstance().getPassword();
        onChanged();
        return this;
      }

      private long identifier_ ;
      /**
       * <code>optional uint64 identifier = 2;</code>
       */
      public boolean hasIdentifier() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional uint64 identifier = 2;</code>
       */
      public long getIdentifier() {
        return identifier_;
      }
      /**
       * <code>optional uint64 identifier = 2;</code>
       */
      public Builder setIdentifier(long value) {
        bitField0_ |= 0x00000002;
        identifier_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 identifier = 2;</code>
       */
      public Builder clearIdentifier() {
        bitField0_ = (bitField0_ & ~0x00000002);
        identifier_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString payload_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes payload = 3;</code>
       */
      public boolean hasPayload() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional bytes payload = 3;</code>
       */
      public com.google.protobuf.ByteString getPayload() {
        return payload_;
      }
      /**
       * <code>optional bytes payload = 3;</code>
       */
      public Builder setPayload(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        payload_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes payload = 3;</code>
       */
      public Builder clearPayload() {
        bitField0_ = (bitField0_ & ~0x00000004);
        payload_ = getDefaultInstance().getPayload();
        onChanged();
        return this;
      }

      private int timestamp_ ;
      /**
       * <code>optional uint32 timestamp = 4;</code>
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional uint32 timestamp = 4;</code>
       */
      public int getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>optional uint32 timestamp = 4;</code>
       */
      public Builder setTimestamp(int value) {
        bitField0_ |= 0x00000008;
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 timestamp = 4;</code>
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000008);
        timestamp_ = 0;
        onChanged();
        return this;
      }

      private SteammessagesSecretsSteamclient.EKeyEscrowUsage usage_ = SteammessagesSecretsSteamclient.EKeyEscrowUsage.k_EKeyEscrowUsageStreamingDevice;
      /**
       * <code>optional .EKeyEscrowUsage usage = 5 [default = k_EKeyEscrowUsageStreamingDevice];</code>
       */
      public boolean hasUsage() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional .EKeyEscrowUsage usage = 5 [default = k_EKeyEscrowUsageStreamingDevice];</code>
       */
      public SteammessagesSecretsSteamclient.EKeyEscrowUsage getUsage() {
        return usage_;
      }
      /**
       * <code>optional .EKeyEscrowUsage usage = 5 [default = k_EKeyEscrowUsageStreamingDevice];</code>
       */
      public Builder setUsage(SteammessagesSecretsSteamclient.EKeyEscrowUsage value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000010;
        usage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .EKeyEscrowUsage usage = 5 [default = k_EKeyEscrowUsageStreamingDevice];</code>
       */
      public Builder clearUsage() {
        bitField0_ = (bitField0_ & ~0x00000010);
        usage_ = SteammessagesSecretsSteamclient.EKeyEscrowUsage.k_EKeyEscrowUsageStreamingDevice;
        onChanged();
        return this;
      }

      private java.lang.Object deviceName_ = "";
      /**
       * <code>optional string device_name = 6;</code>
       */
      public boolean hasDeviceName() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string device_name = 6;</code>
       */
      public java.lang.String getDeviceName() {
        java.lang.Object ref = deviceName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            deviceName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string device_name = 6;</code>
       */
      public com.google.protobuf.ByteString
          getDeviceNameBytes() {
        java.lang.Object ref = deviceName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          deviceName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string device_name = 6;</code>
       */
      public Builder setDeviceName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        deviceName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string device_name = 6;</code>
       */
      public Builder clearDeviceName() {
        bitField0_ = (bitField0_ & ~0x00000020);
        deviceName_ = getDefaultInstance().getDeviceName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string device_name = 6;</code>
       */
      public Builder setDeviceNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        deviceName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object deviceModel_ = "";
      /**
       * <code>optional string device_model = 7;</code>
       */
      public boolean hasDeviceModel() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional string device_model = 7;</code>
       */
      public java.lang.String getDeviceModel() {
        java.lang.Object ref = deviceModel_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            deviceModel_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string device_model = 7;</code>
       */
      public com.google.protobuf.ByteString
          getDeviceModelBytes() {
        java.lang.Object ref = deviceModel_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          deviceModel_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string device_model = 7;</code>
       */
      public Builder setDeviceModel(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        deviceModel_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string device_model = 7;</code>
       */
      public Builder clearDeviceModel() {
        bitField0_ = (bitField0_ & ~0x00000040);
        deviceModel_ = getDefaultInstance().getDeviceModel();
        onChanged();
        return this;
      }
      /**
       * <code>optional string device_model = 7;</code>
       */
      public Builder setDeviceModelBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        deviceModel_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object deviceSerial_ = "";
      /**
       * <code>optional string device_serial = 8;</code>
       */
      public boolean hasDeviceSerial() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional string device_serial = 8;</code>
       */
      public java.lang.String getDeviceSerial() {
        java.lang.Object ref = deviceSerial_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            deviceSerial_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string device_serial = 8;</code>
       */
      public com.google.protobuf.ByteString
          getDeviceSerialBytes() {
        java.lang.Object ref = deviceSerial_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          deviceSerial_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string device_serial = 8;</code>
       */
      public Builder setDeviceSerial(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        deviceSerial_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string device_serial = 8;</code>
       */
      public Builder clearDeviceSerial() {
        bitField0_ = (bitField0_ & ~0x00000080);
        deviceSerial_ = getDefaultInstance().getDeviceSerial();
        onChanged();
        return this;
      }
      /**
       * <code>optional string device_serial = 8;</code>
       */
      public Builder setDeviceSerialBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        deviceSerial_ = value;
        onChanged();
        return this;
      }

      private int deviceProvisioningId_ ;
      /**
       * <code>optional uint32 device_provisioning_id = 9;</code>
       */
      public boolean hasDeviceProvisioningId() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional uint32 device_provisioning_id = 9;</code>
       */
      public int getDeviceProvisioningId() {
        return deviceProvisioningId_;
      }
      /**
       * <code>optional uint32 device_provisioning_id = 9;</code>
       */
      public Builder setDeviceProvisioningId(int value) {
        bitField0_ |= 0x00000100;
        deviceProvisioningId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 device_provisioning_id = 9;</code>
       */
      public Builder clearDeviceProvisioningId() {
        bitField0_ = (bitField0_ & ~0x00000100);
        deviceProvisioningId_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:CKeyEscrow_Ticket)
    }

    static {
      defaultInstance = new CKeyEscrow_Ticket(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:CKeyEscrow_Ticket)
  }

  public interface CKeyEscrow_ResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CKeyEscrow_Response)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .CKeyEscrow_Ticket ticket = 1;</code>
     */
    boolean hasTicket();
    /**
     * <code>optional .CKeyEscrow_Ticket ticket = 1;</code>
     */
    SteammessagesSecretsSteamclient.CKeyEscrow_Ticket getTicket();
    /**
     * <code>optional .CKeyEscrow_Ticket ticket = 1;</code>
     */
    SteammessagesSecretsSteamclient.CKeyEscrow_TicketOrBuilder getTicketOrBuilder();
  }
  /**
   * Protobuf type {@code CKeyEscrow_Response}
   */
  public static final class CKeyEscrow_Response extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:CKeyEscrow_Response)
      CKeyEscrow_ResponseOrBuilder {
    // Use CKeyEscrow_Response.newBuilder() to construct.
    private CKeyEscrow_Response(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CKeyEscrow_Response(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CKeyEscrow_Response defaultInstance;
    public static CKeyEscrow_Response getDefaultInstance() {
      return defaultInstance;
    }

    public CKeyEscrow_Response getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CKeyEscrow_Response(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              SteammessagesSecretsSteamclient.CKeyEscrow_Ticket.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = ticket_.toBuilder();
              }
              ticket_ = input.readMessage(SteammessagesSecretsSteamclient.CKeyEscrow_Ticket.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(ticket_);
                ticket_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SteammessagesSecretsSteamclient.internal_static_CKeyEscrow_Response_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SteammessagesSecretsSteamclient.internal_static_CKeyEscrow_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SteammessagesSecretsSteamclient.CKeyEscrow_Response.class, SteammessagesSecretsSteamclient.CKeyEscrow_Response.Builder.class);
    }

    public static com.google.protobuf.Parser<CKeyEscrow_Response> PARSER =
        new com.google.protobuf.AbstractParser<CKeyEscrow_Response>() {
      public CKeyEscrow_Response parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CKeyEscrow_Response(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CKeyEscrow_Response> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int TICKET_FIELD_NUMBER = 1;
    private SteammessagesSecretsSteamclient.CKeyEscrow_Ticket ticket_;
    /**
     * <code>optional .CKeyEscrow_Ticket ticket = 1;</code>
     */
    public boolean hasTicket() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .CKeyEscrow_Ticket ticket = 1;</code>
     */
    public SteammessagesSecretsSteamclient.CKeyEscrow_Ticket getTicket() {
      return ticket_;
    }
    /**
     * <code>optional .CKeyEscrow_Ticket ticket = 1;</code>
     */
    public SteammessagesSecretsSteamclient.CKeyEscrow_TicketOrBuilder getTicketOrBuilder() {
      return ticket_;
    }

    private void initFields() {
      ticket_ = SteammessagesSecretsSteamclient.CKeyEscrow_Ticket.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, ticket_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, ticket_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static SteammessagesSecretsSteamclient.CKeyEscrow_Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SteammessagesSecretsSteamclient.CKeyEscrow_Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SteammessagesSecretsSteamclient.CKeyEscrow_Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SteammessagesSecretsSteamclient.CKeyEscrow_Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SteammessagesSecretsSteamclient.CKeyEscrow_Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static SteammessagesSecretsSteamclient.CKeyEscrow_Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static SteammessagesSecretsSteamclient.CKeyEscrow_Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static SteammessagesSecretsSteamclient.CKeyEscrow_Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static SteammessagesSecretsSteamclient.CKeyEscrow_Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static SteammessagesSecretsSteamclient.CKeyEscrow_Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(SteammessagesSecretsSteamclient.CKeyEscrow_Response prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CKeyEscrow_Response}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CKeyEscrow_Response)
        SteammessagesSecretsSteamclient.CKeyEscrow_ResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SteammessagesSecretsSteamclient.internal_static_CKeyEscrow_Response_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SteammessagesSecretsSteamclient.internal_static_CKeyEscrow_Response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                SteammessagesSecretsSteamclient.CKeyEscrow_Response.class, SteammessagesSecretsSteamclient.CKeyEscrow_Response.Builder.class);
      }

      // Construct using SteammessagesSecretsSteamclient.CKeyEscrow_Response.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getTicketFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (ticketBuilder_ == null) {
          ticket_ = SteammessagesSecretsSteamclient.CKeyEscrow_Ticket.getDefaultInstance();
        } else {
          ticketBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SteammessagesSecretsSteamclient.internal_static_CKeyEscrow_Response_descriptor;
      }

      public SteammessagesSecretsSteamclient.CKeyEscrow_Response getDefaultInstanceForType() {
        return SteammessagesSecretsSteamclient.CKeyEscrow_Response.getDefaultInstance();
      }

      public SteammessagesSecretsSteamclient.CKeyEscrow_Response build() {
        SteammessagesSecretsSteamclient.CKeyEscrow_Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public SteammessagesSecretsSteamclient.CKeyEscrow_Response buildPartial() {
        SteammessagesSecretsSteamclient.CKeyEscrow_Response result = new SteammessagesSecretsSteamclient.CKeyEscrow_Response(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (ticketBuilder_ == null) {
          result.ticket_ = ticket_;
        } else {
          result.ticket_ = ticketBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof SteammessagesSecretsSteamclient.CKeyEscrow_Response) {
          return mergeFrom((SteammessagesSecretsSteamclient.CKeyEscrow_Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(SteammessagesSecretsSteamclient.CKeyEscrow_Response other) {
        if (other == SteammessagesSecretsSteamclient.CKeyEscrow_Response.getDefaultInstance()) return this;
        if (other.hasTicket()) {
          mergeTicket(other.getTicket());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        SteammessagesSecretsSteamclient.CKeyEscrow_Response parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (SteammessagesSecretsSteamclient.CKeyEscrow_Response) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private SteammessagesSecretsSteamclient.CKeyEscrow_Ticket ticket_ = SteammessagesSecretsSteamclient.CKeyEscrow_Ticket.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          SteammessagesSecretsSteamclient.CKeyEscrow_Ticket, SteammessagesSecretsSteamclient.CKeyEscrow_Ticket.Builder, SteammessagesSecretsSteamclient.CKeyEscrow_TicketOrBuilder> ticketBuilder_;
      /**
       * <code>optional .CKeyEscrow_Ticket ticket = 1;</code>
       */
      public boolean hasTicket() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .CKeyEscrow_Ticket ticket = 1;</code>
       */
      public SteammessagesSecretsSteamclient.CKeyEscrow_Ticket getTicket() {
        if (ticketBuilder_ == null) {
          return ticket_;
        } else {
          return ticketBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .CKeyEscrow_Ticket ticket = 1;</code>
       */
      public Builder setTicket(SteammessagesSecretsSteamclient.CKeyEscrow_Ticket value) {
        if (ticketBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ticket_ = value;
          onChanged();
        } else {
          ticketBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .CKeyEscrow_Ticket ticket = 1;</code>
       */
      public Builder setTicket(
          SteammessagesSecretsSteamclient.CKeyEscrow_Ticket.Builder builderForValue) {
        if (ticketBuilder_ == null) {
          ticket_ = builderForValue.build();
          onChanged();
        } else {
          ticketBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .CKeyEscrow_Ticket ticket = 1;</code>
       */
      public Builder mergeTicket(SteammessagesSecretsSteamclient.CKeyEscrow_Ticket value) {
        if (ticketBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              ticket_ != SteammessagesSecretsSteamclient.CKeyEscrow_Ticket.getDefaultInstance()) {
            ticket_ =
              SteammessagesSecretsSteamclient.CKeyEscrow_Ticket.newBuilder(ticket_).mergeFrom(value).buildPartial();
          } else {
            ticket_ = value;
          }
          onChanged();
        } else {
          ticketBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .CKeyEscrow_Ticket ticket = 1;</code>
       */
      public Builder clearTicket() {
        if (ticketBuilder_ == null) {
          ticket_ = SteammessagesSecretsSteamclient.CKeyEscrow_Ticket.getDefaultInstance();
          onChanged();
        } else {
          ticketBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .CKeyEscrow_Ticket ticket = 1;</code>
       */
      public SteammessagesSecretsSteamclient.CKeyEscrow_Ticket.Builder getTicketBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getTicketFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .CKeyEscrow_Ticket ticket = 1;</code>
       */
      public SteammessagesSecretsSteamclient.CKeyEscrow_TicketOrBuilder getTicketOrBuilder() {
        if (ticketBuilder_ != null) {
          return ticketBuilder_.getMessageOrBuilder();
        } else {
          return ticket_;
        }
      }
      /**
       * <code>optional .CKeyEscrow_Ticket ticket = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          SteammessagesSecretsSteamclient.CKeyEscrow_Ticket, SteammessagesSecretsSteamclient.CKeyEscrow_Ticket.Builder, SteammessagesSecretsSteamclient.CKeyEscrow_TicketOrBuilder> 
          getTicketFieldBuilder() {
        if (ticketBuilder_ == null) {
          ticketBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              SteammessagesSecretsSteamclient.CKeyEscrow_Ticket, SteammessagesSecretsSteamclient.CKeyEscrow_Ticket.Builder, SteammessagesSecretsSteamclient.CKeyEscrow_TicketOrBuilder>(
                  getTicket(),
                  getParentForChildren(),
                  isClean());
          ticket_ = null;
        }
        return ticketBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:CKeyEscrow_Response)
    }

    static {
      defaultInstance = new CKeyEscrow_Response(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:CKeyEscrow_Response)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CKeyEscrow_Request_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CKeyEscrow_Request_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CKeyEscrow_Ticket_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CKeyEscrow_Ticket_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CKeyEscrow_Response_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CKeyEscrow_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\'steammessages_secrets.steamclient.prot" +
      "o\032,steammessages_unified_base.steamclien" +
      "t.proto\"\233\001\n\022CKeyEscrow_Request\022\033\n\023rsa_oa" +
      "ep_sha_ticket\030\001 \001(\014\022\020\n\010password\030\002 \001(\014\022A\n" +
      "\005usage\030\003 \001(\0162\020.EKeyEscrowUsage: k_EKeyEs" +
      "crowUsageStreamingDevice\022\023\n\013device_name\030" +
      "\004 \001(\t\"\202\002\n\021CKeyEscrow_Ticket\022\020\n\010password\030" +
      "\001 \001(\014\022\022\n\nidentifier\030\002 \001(\004\022\017\n\007payload\030\003 \001" +
      "(\014\022\021\n\ttimestamp\030\004 \001(\r\022A\n\005usage\030\005 \001(\0162\020.E" +
      "KeyEscrowUsage: k_EKeyEscrowUsageStreami",
      "ngDevice\022\023\n\013device_name\030\006 \001(\t\022\024\n\014device_" +
      "model\030\007 \001(\t\022\025\n\rdevice_serial\030\010 \001(\t\022\036\n\026de" +
      "vice_provisioning_id\030\t \001(\r\"9\n\023CKeyEscrow" +
      "_Response\022\"\n\006ticket\030\001 \001(\0132\022.CKeyEscrow_T" +
      "icket*7\n\017EKeyEscrowUsage\022$\n k_EKeyEscrow" +
      "UsageStreamingDevice\020\0002\310\001\n\007Secrets\022\200\001\n\tK" +
      "eyEscrow\022\023.CKeyEscrow_Request\032\024.CKeyEscr" +
      "ow_Response\"H\202\265\030DService to perform auth" +
      "enticated key-exchange involving Steam C" +
      "lient\032:\202\265\0306Service for accessing credent",
      "ials and guarding secretsB\003\200\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          SteammessagesUnifiedBaseSteamclient.getDescriptor(),
        }, assigner);
    internal_static_CKeyEscrow_Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CKeyEscrow_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_CKeyEscrow_Request_descriptor,
        new java.lang.String[] { "RsaOaepShaTicket", "Password", "Usage", "DeviceName", });
    internal_static_CKeyEscrow_Ticket_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_CKeyEscrow_Ticket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_CKeyEscrow_Ticket_descriptor,
        new java.lang.String[] { "Password", "Identifier", "Payload", "Timestamp", "Usage", "DeviceName", "DeviceModel", "DeviceSerial", "DeviceProvisioningId", });
    internal_static_CKeyEscrow_Response_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_CKeyEscrow_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_CKeyEscrow_Response_descriptor,
        new java.lang.String[] { "Ticket", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(SteammessagesUnifiedBaseSteamclient.methodDescription);
    registry.add(SteammessagesUnifiedBaseSteamclient.serviceDescription);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    SteammessagesUnifiedBaseSteamclient.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
