// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: steammessages_store.steamclient.proto
package com.jsteamkit.internals.proto;

public final class SteammessagesStoreSteamclient {
  private SteammessagesStoreSteamclient() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CStore_GetLocalizedNameForTags_RequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CStore_GetLocalizedNameForTags_Request)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string language = 1;</code>
     */
    boolean hasLanguage();
    /**
     * <code>optional string language = 1;</code>
     */
    java.lang.String getLanguage();
    /**
     * <code>optional string language = 1;</code>
     */
    com.google.protobuf.ByteString
        getLanguageBytes();

    /**
     * <code>repeated uint32 tagids = 2;</code>
     */
    java.util.List<java.lang.Integer> getTagidsList();
    /**
     * <code>repeated uint32 tagids = 2;</code>
     */
    int getTagidsCount();
    /**
     * <code>repeated uint32 tagids = 2;</code>
     */
    int getTagids(int index);
  }
  /**
   * Protobuf type {@code CStore_GetLocalizedNameForTags_Request}
   */
  public  static final class CStore_GetLocalizedNameForTags_Request extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:CStore_GetLocalizedNameForTags_Request)
      CStore_GetLocalizedNameForTags_RequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CStore_GetLocalizedNameForTags_Request.newBuilder() to construct.
    private CStore_GetLocalizedNameForTags_Request(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CStore_GetLocalizedNameForTags_Request() {
      language_ = "";
      tagids_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CStore_GetLocalizedNameForTags_Request(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              language_ = bs;
              break;
            }
            case 16: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                tagids_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000002;
              }
              tagids_.add(input.readUInt32());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002) && input.getBytesUntilLimit() > 0) {
                tagids_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000002;
              }
              while (input.getBytesUntilLimit() > 0) {
                tagids_.add(input.readUInt32());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          tagids_ = java.util.Collections.unmodifiableList(tagids_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SteammessagesStoreSteamclient.internal_static_CStore_GetLocalizedNameForTags_Request_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SteammessagesStoreSteamclient.internal_static_CStore_GetLocalizedNameForTags_Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Request.class, SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Request.Builder.class);
    }

    private int bitField0_;
    public static final int LANGUAGE_FIELD_NUMBER = 1;
    private volatile java.lang.Object language_;
    /**
     * <code>optional string language = 1;</code>
     */
    public boolean hasLanguage() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string language = 1;</code>
     */
    public java.lang.String getLanguage() {
      java.lang.Object ref = language_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          language_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string language = 1;</code>
     */
    public com.google.protobuf.ByteString
        getLanguageBytes() {
      java.lang.Object ref = language_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        language_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TAGIDS_FIELD_NUMBER = 2;
    private java.util.List<java.lang.Integer> tagids_;
    /**
     * <code>repeated uint32 tagids = 2;</code>
     */
    public java.util.List<java.lang.Integer>
        getTagidsList() {
      return tagids_;
    }
    /**
     * <code>repeated uint32 tagids = 2;</code>
     */
    public int getTagidsCount() {
      return tagids_.size();
    }
    /**
     * <code>repeated uint32 tagids = 2;</code>
     */
    public int getTagids(int index) {
      return tagids_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, language_);
      }
      for (int i = 0; i < tagids_.size(); i++) {
        output.writeUInt32(2, tagids_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, language_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < tagids_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeUInt32SizeNoTag(tagids_.get(i));
        }
        size += dataSize;
        size += 1 * getTagidsList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Request)) {
        return super.equals(obj);
      }
      SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Request other = (SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Request) obj;

      boolean result = true;
      result = result && (hasLanguage() == other.hasLanguage());
      if (hasLanguage()) {
        result = result && getLanguage()
            .equals(other.getLanguage());
      }
      result = result && getTagidsList()
          .equals(other.getTagidsList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasLanguage()) {
        hash = (37 * hash) + LANGUAGE_FIELD_NUMBER;
        hash = (53 * hash) + getLanguage().hashCode();
      }
      if (getTagidsCount() > 0) {
        hash = (37 * hash) + TAGIDS_FIELD_NUMBER;
        hash = (53 * hash) + getTagidsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Request parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Request parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Request prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CStore_GetLocalizedNameForTags_Request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CStore_GetLocalizedNameForTags_Request)
        SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_RequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SteammessagesStoreSteamclient.internal_static_CStore_GetLocalizedNameForTags_Request_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SteammessagesStoreSteamclient.internal_static_CStore_GetLocalizedNameForTags_Request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Request.class, SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Request.Builder.class);
      }

      // Construct using SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        language_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        tagids_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SteammessagesStoreSteamclient.internal_static_CStore_GetLocalizedNameForTags_Request_descriptor;
      }

      public SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Request getDefaultInstanceForType() {
        return SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Request.getDefaultInstance();
      }

      public SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Request build() {
        SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Request buildPartial() {
        SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Request result = new SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Request(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.language_ = language_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          tagids_ = java.util.Collections.unmodifiableList(tagids_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.tagids_ = tagids_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Request) {
          return mergeFrom((SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Request other) {
        if (other == SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Request.getDefaultInstance()) return this;
        if (other.hasLanguage()) {
          bitField0_ |= 0x00000001;
          language_ = other.language_;
          onChanged();
        }
        if (!other.tagids_.isEmpty()) {
          if (tagids_.isEmpty()) {
            tagids_ = other.tagids_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureTagidsIsMutable();
            tagids_.addAll(other.tagids_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Request parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Request) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object language_ = "";
      /**
       * <code>optional string language = 1;</code>
       */
      public boolean hasLanguage() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string language = 1;</code>
       */
      public java.lang.String getLanguage() {
        java.lang.Object ref = language_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            language_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string language = 1;</code>
       */
      public com.google.protobuf.ByteString
          getLanguageBytes() {
        java.lang.Object ref = language_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          language_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string language = 1;</code>
       */
      public Builder setLanguage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        language_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string language = 1;</code>
       */
      public Builder clearLanguage() {
        bitField0_ = (bitField0_ & ~0x00000001);
        language_ = getDefaultInstance().getLanguage();
        onChanged();
        return this;
      }
      /**
       * <code>optional string language = 1;</code>
       */
      public Builder setLanguageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        language_ = value;
        onChanged();
        return this;
      }

      private java.util.List<java.lang.Integer> tagids_ = java.util.Collections.emptyList();
      private void ensureTagidsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          tagids_ = new java.util.ArrayList<java.lang.Integer>(tagids_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated uint32 tagids = 2;</code>
       */
      public java.util.List<java.lang.Integer>
          getTagidsList() {
        return java.util.Collections.unmodifiableList(tagids_);
      }
      /**
       * <code>repeated uint32 tagids = 2;</code>
       */
      public int getTagidsCount() {
        return tagids_.size();
      }
      /**
       * <code>repeated uint32 tagids = 2;</code>
       */
      public int getTagids(int index) {
        return tagids_.get(index);
      }
      /**
       * <code>repeated uint32 tagids = 2;</code>
       */
      public Builder setTagids(
          int index, int value) {
        ensureTagidsIsMutable();
        tagids_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint32 tagids = 2;</code>
       */
      public Builder addTagids(int value) {
        ensureTagidsIsMutable();
        tagids_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint32 tagids = 2;</code>
       */
      public Builder addAllTagids(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureTagidsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, tagids_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint32 tagids = 2;</code>
       */
      public Builder clearTagids() {
        tagids_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:CStore_GetLocalizedNameForTags_Request)
    }

    // @@protoc_insertion_point(class_scope:CStore_GetLocalizedNameForTags_Request)
    private static final SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Request DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Request();
    }

    public static SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Request getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<CStore_GetLocalizedNameForTags_Request>
        PARSER = new com.google.protobuf.AbstractParser<CStore_GetLocalizedNameForTags_Request>() {
      public CStore_GetLocalizedNameForTags_Request parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new CStore_GetLocalizedNameForTags_Request(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CStore_GetLocalizedNameForTags_Request> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CStore_GetLocalizedNameForTags_Request> getParserForType() {
      return PARSER;
    }

    public SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Request getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CStore_GetLocalizedNameForTags_ResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CStore_GetLocalizedNameForTags_Response)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .CStore_GetLocalizedNameForTags_Response.Tag tags = 1;</code>
     */
    java.util.List<SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Response.Tag> 
        getTagsList();
    /**
     * <code>repeated .CStore_GetLocalizedNameForTags_Response.Tag tags = 1;</code>
     */
    SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Response.Tag getTags(int index);
    /**
     * <code>repeated .CStore_GetLocalizedNameForTags_Response.Tag tags = 1;</code>
     */
    int getTagsCount();
    /**
     * <code>repeated .CStore_GetLocalizedNameForTags_Response.Tag tags = 1;</code>
     */
    java.util.List<? extends SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Response.TagOrBuilder> 
        getTagsOrBuilderList();
    /**
     * <code>repeated .CStore_GetLocalizedNameForTags_Response.Tag tags = 1;</code>
     */
    SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Response.TagOrBuilder getTagsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code CStore_GetLocalizedNameForTags_Response}
   */
  public  static final class CStore_GetLocalizedNameForTags_Response extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:CStore_GetLocalizedNameForTags_Response)
      CStore_GetLocalizedNameForTags_ResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CStore_GetLocalizedNameForTags_Response.newBuilder() to construct.
    private CStore_GetLocalizedNameForTags_Response(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CStore_GetLocalizedNameForTags_Response() {
      tags_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CStore_GetLocalizedNameForTags_Response(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                tags_ = new java.util.ArrayList<SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Response.Tag>();
                mutable_bitField0_ |= 0x00000001;
              }
              tags_.add(
                  input.readMessage(SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Response.Tag.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          tags_ = java.util.Collections.unmodifiableList(tags_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SteammessagesStoreSteamclient.internal_static_CStore_GetLocalizedNameForTags_Response_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SteammessagesStoreSteamclient.internal_static_CStore_GetLocalizedNameForTags_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Response.class, SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Response.Builder.class);
    }

    public interface TagOrBuilder extends
        // @@protoc_insertion_point(interface_extends:CStore_GetLocalizedNameForTags_Response.Tag)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>optional uint32 tagid = 1;</code>
       */
      boolean hasTagid();
      /**
       * <code>optional uint32 tagid = 1;</code>
       */
      int getTagid();

      /**
       * <code>optional string english_name = 2;</code>
       */
      boolean hasEnglishName();
      /**
       * <code>optional string english_name = 2;</code>
       */
      java.lang.String getEnglishName();
      /**
       * <code>optional string english_name = 2;</code>
       */
      com.google.protobuf.ByteString
          getEnglishNameBytes();

      /**
       * <code>optional string name = 3;</code>
       */
      boolean hasName();
      /**
       * <code>optional string name = 3;</code>
       */
      java.lang.String getName();
      /**
       * <code>optional string name = 3;</code>
       */
      com.google.protobuf.ByteString
          getNameBytes();
    }
    /**
     * Protobuf type {@code CStore_GetLocalizedNameForTags_Response.Tag}
     */
    public  static final class Tag extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:CStore_GetLocalizedNameForTags_Response.Tag)
        TagOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use Tag.newBuilder() to construct.
      private Tag(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Tag() {
        tagid_ = 0;
        englishName_ = "";
        name_ = "";
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private Tag(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 8: {
                bitField0_ |= 0x00000001;
                tagid_ = input.readUInt32();
                break;
              }
              case 18: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000002;
                englishName_ = bs;
                break;
              }
              case 26: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000004;
                name_ = bs;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SteammessagesStoreSteamclient.internal_static_CStore_GetLocalizedNameForTags_Response_Tag_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SteammessagesStoreSteamclient.internal_static_CStore_GetLocalizedNameForTags_Response_Tag_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Response.Tag.class, SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Response.Tag.Builder.class);
      }

      private int bitField0_;
      public static final int TAGID_FIELD_NUMBER = 1;
      private int tagid_;
      /**
       * <code>optional uint32 tagid = 1;</code>
       */
      public boolean hasTagid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional uint32 tagid = 1;</code>
       */
      public int getTagid() {
        return tagid_;
      }

      public static final int ENGLISH_NAME_FIELD_NUMBER = 2;
      private volatile java.lang.Object englishName_;
      /**
       * <code>optional string english_name = 2;</code>
       */
      public boolean hasEnglishName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string english_name = 2;</code>
       */
      public java.lang.String getEnglishName() {
        java.lang.Object ref = englishName_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            englishName_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string english_name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getEnglishNameBytes() {
        java.lang.Object ref = englishName_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          englishName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int NAME_FIELD_NUMBER = 3;
      private volatile java.lang.Object name_;
      /**
       * <code>optional string name = 3;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string name = 3;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string name = 3;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeUInt32(1, tagid_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 2, englishName_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 3, name_);
        }
        unknownFields.writeTo(output);
      }

      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt32Size(1, tagid_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, englishName_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, name_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Response.Tag)) {
          return super.equals(obj);
        }
        SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Response.Tag other = (SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Response.Tag) obj;

        boolean result = true;
        result = result && (hasTagid() == other.hasTagid());
        if (hasTagid()) {
          result = result && (getTagid()
              == other.getTagid());
        }
        result = result && (hasEnglishName() == other.hasEnglishName());
        if (hasEnglishName()) {
          result = result && getEnglishName()
              .equals(other.getEnglishName());
        }
        result = result && (hasName() == other.hasName());
        if (hasName()) {
          result = result && getName()
              .equals(other.getName());
        }
        result = result && unknownFields.equals(other.unknownFields);
        return result;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (hasTagid()) {
          hash = (37 * hash) + TAGID_FIELD_NUMBER;
          hash = (53 * hash) + getTagid();
        }
        if (hasEnglishName()) {
          hash = (37 * hash) + ENGLISH_NAME_FIELD_NUMBER;
          hash = (53 * hash) + getEnglishName().hashCode();
        }
        if (hasName()) {
          hash = (37 * hash) + NAME_FIELD_NUMBER;
          hash = (53 * hash) + getName().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Response.Tag parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Response.Tag parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Response.Tag parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Response.Tag parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Response.Tag parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Response.Tag parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Response.Tag parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Response.Tag parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Response.Tag parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Response.Tag parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Response.Tag parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Response.Tag parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Response.Tag prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code CStore_GetLocalizedNameForTags_Response.Tag}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:CStore_GetLocalizedNameForTags_Response.Tag)
          SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Response.TagOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return SteammessagesStoreSteamclient.internal_static_CStore_GetLocalizedNameForTags_Response_Tag_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return SteammessagesStoreSteamclient.internal_static_CStore_GetLocalizedNameForTags_Response_Tag_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Response.Tag.class, SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Response.Tag.Builder.class);
        }

        // Construct using SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Response.Tag.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        public Builder clear() {
          super.clear();
          tagid_ = 0;
          bitField0_ = (bitField0_ & ~0x00000001);
          englishName_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          name_ = "";
          bitField0_ = (bitField0_ & ~0x00000004);
          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return SteammessagesStoreSteamclient.internal_static_CStore_GetLocalizedNameForTags_Response_Tag_descriptor;
        }

        public SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Response.Tag getDefaultInstanceForType() {
          return SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Response.Tag.getDefaultInstance();
        }

        public SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Response.Tag build() {
          SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Response.Tag result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Response.Tag buildPartial() {
          SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Response.Tag result = new SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Response.Tag(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.tagid_ = tagid_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.englishName_ = englishName_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.name_ = name_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder clone() {
          return (Builder) super.clone();
        }
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.setField(field, value);
        }
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Response.Tag) {
            return mergeFrom((SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Response.Tag)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Response.Tag other) {
          if (other == SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Response.Tag.getDefaultInstance()) return this;
          if (other.hasTagid()) {
            setTagid(other.getTagid());
          }
          if (other.hasEnglishName()) {
            bitField0_ |= 0x00000002;
            englishName_ = other.englishName_;
            onChanged();
          }
          if (other.hasName()) {
            bitField0_ |= 0x00000004;
            name_ = other.name_;
            onChanged();
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Response.Tag parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Response.Tag) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private int tagid_ ;
        /**
         * <code>optional uint32 tagid = 1;</code>
         */
        public boolean hasTagid() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>optional uint32 tagid = 1;</code>
         */
        public int getTagid() {
          return tagid_;
        }
        /**
         * <code>optional uint32 tagid = 1;</code>
         */
        public Builder setTagid(int value) {
          bitField0_ |= 0x00000001;
          tagid_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional uint32 tagid = 1;</code>
         */
        public Builder clearTagid() {
          bitField0_ = (bitField0_ & ~0x00000001);
          tagid_ = 0;
          onChanged();
          return this;
        }

        private java.lang.Object englishName_ = "";
        /**
         * <code>optional string english_name = 2;</code>
         */
        public boolean hasEnglishName() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>optional string english_name = 2;</code>
         */
        public java.lang.String getEnglishName() {
          java.lang.Object ref = englishName_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              englishName_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string english_name = 2;</code>
         */
        public com.google.protobuf.ByteString
            getEnglishNameBytes() {
          java.lang.Object ref = englishName_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            englishName_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string english_name = 2;</code>
         */
        public Builder setEnglishName(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          englishName_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string english_name = 2;</code>
         */
        public Builder clearEnglishName() {
          bitField0_ = (bitField0_ & ~0x00000002);
          englishName_ = getDefaultInstance().getEnglishName();
          onChanged();
          return this;
        }
        /**
         * <code>optional string english_name = 2;</code>
         */
        public Builder setEnglishNameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          englishName_ = value;
          onChanged();
          return this;
        }

        private java.lang.Object name_ = "";
        /**
         * <code>optional string name = 3;</code>
         */
        public boolean hasName() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        /**
         * <code>optional string name = 3;</code>
         */
        public java.lang.String getName() {
          java.lang.Object ref = name_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              name_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string name = 3;</code>
         */
        public com.google.protobuf.ByteString
            getNameBytes() {
          java.lang.Object ref = name_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            name_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string name = 3;</code>
         */
        public Builder setName(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
          name_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string name = 3;</code>
         */
        public Builder clearName() {
          bitField0_ = (bitField0_ & ~0x00000004);
          name_ = getDefaultInstance().getName();
          onChanged();
          return this;
        }
        /**
         * <code>optional string name = 3;</code>
         */
        public Builder setNameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
          name_ = value;
          onChanged();
          return this;
        }
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:CStore_GetLocalizedNameForTags_Response.Tag)
      }

      // @@protoc_insertion_point(class_scope:CStore_GetLocalizedNameForTags_Response.Tag)
      private static final SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Response.Tag DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Response.Tag();
      }

      public static SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Response.Tag getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      @java.lang.Deprecated public static final com.google.protobuf.Parser<Tag>
          PARSER = new com.google.protobuf.AbstractParser<Tag>() {
        public Tag parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return new Tag(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Tag> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Tag> getParserForType() {
        return PARSER;
      }

      public SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Response.Tag getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int TAGS_FIELD_NUMBER = 1;
    private java.util.List<SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Response.Tag> tags_;
    /**
     * <code>repeated .CStore_GetLocalizedNameForTags_Response.Tag tags = 1;</code>
     */
    public java.util.List<SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Response.Tag> getTagsList() {
      return tags_;
    }
    /**
     * <code>repeated .CStore_GetLocalizedNameForTags_Response.Tag tags = 1;</code>
     */
    public java.util.List<? extends SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Response.TagOrBuilder> 
        getTagsOrBuilderList() {
      return tags_;
    }
    /**
     * <code>repeated .CStore_GetLocalizedNameForTags_Response.Tag tags = 1;</code>
     */
    public int getTagsCount() {
      return tags_.size();
    }
    /**
     * <code>repeated .CStore_GetLocalizedNameForTags_Response.Tag tags = 1;</code>
     */
    public SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Response.Tag getTags(int index) {
      return tags_.get(index);
    }
    /**
     * <code>repeated .CStore_GetLocalizedNameForTags_Response.Tag tags = 1;</code>
     */
    public SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Response.TagOrBuilder getTagsOrBuilder(
        int index) {
      return tags_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < tags_.size(); i++) {
        output.writeMessage(1, tags_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < tags_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, tags_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Response)) {
        return super.equals(obj);
      }
      SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Response other = (SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Response) obj;

      boolean result = true;
      result = result && getTagsList()
          .equals(other.getTagsList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getTagsCount() > 0) {
        hash = (37 * hash) + TAGS_FIELD_NUMBER;
        hash = (53 * hash) + getTagsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Response parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Response parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Response prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CStore_GetLocalizedNameForTags_Response}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CStore_GetLocalizedNameForTags_Response)
        SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_ResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SteammessagesStoreSteamclient.internal_static_CStore_GetLocalizedNameForTags_Response_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SteammessagesStoreSteamclient.internal_static_CStore_GetLocalizedNameForTags_Response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Response.class, SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Response.Builder.class);
      }

      // Construct using SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Response.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getTagsFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (tagsBuilder_ == null) {
          tags_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          tagsBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SteammessagesStoreSteamclient.internal_static_CStore_GetLocalizedNameForTags_Response_descriptor;
      }

      public SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Response getDefaultInstanceForType() {
        return SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Response.getDefaultInstance();
      }

      public SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Response build() {
        SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Response buildPartial() {
        SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Response result = new SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Response(this);
        int from_bitField0_ = bitField0_;
        if (tagsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            tags_ = java.util.Collections.unmodifiableList(tags_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.tags_ = tags_;
        } else {
          result.tags_ = tagsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Response) {
          return mergeFrom((SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Response other) {
        if (other == SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Response.getDefaultInstance()) return this;
        if (tagsBuilder_ == null) {
          if (!other.tags_.isEmpty()) {
            if (tags_.isEmpty()) {
              tags_ = other.tags_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureTagsIsMutable();
              tags_.addAll(other.tags_);
            }
            onChanged();
          }
        } else {
          if (!other.tags_.isEmpty()) {
            if (tagsBuilder_.isEmpty()) {
              tagsBuilder_.dispose();
              tagsBuilder_ = null;
              tags_ = other.tags_;
              bitField0_ = (bitField0_ & ~0x00000001);
              tagsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getTagsFieldBuilder() : null;
            } else {
              tagsBuilder_.addAllMessages(other.tags_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Response parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Response) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Response.Tag> tags_ =
        java.util.Collections.emptyList();
      private void ensureTagsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          tags_ = new java.util.ArrayList<SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Response.Tag>(tags_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Response.Tag, SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Response.Tag.Builder, SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Response.TagOrBuilder> tagsBuilder_;

      /**
       * <code>repeated .CStore_GetLocalizedNameForTags_Response.Tag tags = 1;</code>
       */
      public java.util.List<SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Response.Tag> getTagsList() {
        if (tagsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(tags_);
        } else {
          return tagsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .CStore_GetLocalizedNameForTags_Response.Tag tags = 1;</code>
       */
      public int getTagsCount() {
        if (tagsBuilder_ == null) {
          return tags_.size();
        } else {
          return tagsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .CStore_GetLocalizedNameForTags_Response.Tag tags = 1;</code>
       */
      public SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Response.Tag getTags(int index) {
        if (tagsBuilder_ == null) {
          return tags_.get(index);
        } else {
          return tagsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .CStore_GetLocalizedNameForTags_Response.Tag tags = 1;</code>
       */
      public Builder setTags(
          int index, SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Response.Tag value) {
        if (tagsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTagsIsMutable();
          tags_.set(index, value);
          onChanged();
        } else {
          tagsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .CStore_GetLocalizedNameForTags_Response.Tag tags = 1;</code>
       */
      public Builder setTags(
          int index, SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Response.Tag.Builder builderForValue) {
        if (tagsBuilder_ == null) {
          ensureTagsIsMutable();
          tags_.set(index, builderForValue.build());
          onChanged();
        } else {
          tagsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .CStore_GetLocalizedNameForTags_Response.Tag tags = 1;</code>
       */
      public Builder addTags(SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Response.Tag value) {
        if (tagsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTagsIsMutable();
          tags_.add(value);
          onChanged();
        } else {
          tagsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .CStore_GetLocalizedNameForTags_Response.Tag tags = 1;</code>
       */
      public Builder addTags(
          int index, SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Response.Tag value) {
        if (tagsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTagsIsMutable();
          tags_.add(index, value);
          onChanged();
        } else {
          tagsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .CStore_GetLocalizedNameForTags_Response.Tag tags = 1;</code>
       */
      public Builder addTags(
          SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Response.Tag.Builder builderForValue) {
        if (tagsBuilder_ == null) {
          ensureTagsIsMutable();
          tags_.add(builderForValue.build());
          onChanged();
        } else {
          tagsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .CStore_GetLocalizedNameForTags_Response.Tag tags = 1;</code>
       */
      public Builder addTags(
          int index, SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Response.Tag.Builder builderForValue) {
        if (tagsBuilder_ == null) {
          ensureTagsIsMutable();
          tags_.add(index, builderForValue.build());
          onChanged();
        } else {
          tagsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .CStore_GetLocalizedNameForTags_Response.Tag tags = 1;</code>
       */
      public Builder addAllTags(
          java.lang.Iterable<? extends SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Response.Tag> values) {
        if (tagsBuilder_ == null) {
          ensureTagsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, tags_);
          onChanged();
        } else {
          tagsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .CStore_GetLocalizedNameForTags_Response.Tag tags = 1;</code>
       */
      public Builder clearTags() {
        if (tagsBuilder_ == null) {
          tags_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          tagsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .CStore_GetLocalizedNameForTags_Response.Tag tags = 1;</code>
       */
      public Builder removeTags(int index) {
        if (tagsBuilder_ == null) {
          ensureTagsIsMutable();
          tags_.remove(index);
          onChanged();
        } else {
          tagsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .CStore_GetLocalizedNameForTags_Response.Tag tags = 1;</code>
       */
      public SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Response.Tag.Builder getTagsBuilder(
          int index) {
        return getTagsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .CStore_GetLocalizedNameForTags_Response.Tag tags = 1;</code>
       */
      public SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Response.TagOrBuilder getTagsOrBuilder(
          int index) {
        if (tagsBuilder_ == null) {
          return tags_.get(index);  } else {
          return tagsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .CStore_GetLocalizedNameForTags_Response.Tag tags = 1;</code>
       */
      public java.util.List<? extends SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Response.TagOrBuilder> 
           getTagsOrBuilderList() {
        if (tagsBuilder_ != null) {
          return tagsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(tags_);
        }
      }
      /**
       * <code>repeated .CStore_GetLocalizedNameForTags_Response.Tag tags = 1;</code>
       */
      public SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Response.Tag.Builder addTagsBuilder() {
        return getTagsFieldBuilder().addBuilder(
            SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Response.Tag.getDefaultInstance());
      }
      /**
       * <code>repeated .CStore_GetLocalizedNameForTags_Response.Tag tags = 1;</code>
       */
      public SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Response.Tag.Builder addTagsBuilder(
          int index) {
        return getTagsFieldBuilder().addBuilder(
            index, SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Response.Tag.getDefaultInstance());
      }
      /**
       * <code>repeated .CStore_GetLocalizedNameForTags_Response.Tag tags = 1;</code>
       */
      public java.util.List<SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Response.Tag.Builder> 
           getTagsBuilderList() {
        return getTagsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Response.Tag, SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Response.Tag.Builder, SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Response.TagOrBuilder> 
          getTagsFieldBuilder() {
        if (tagsBuilder_ == null) {
          tagsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Response.Tag, SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Response.Tag.Builder, SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Response.TagOrBuilder>(
                  tags_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          tags_ = null;
        }
        return tagsBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:CStore_GetLocalizedNameForTags_Response)
    }

    // @@protoc_insertion_point(class_scope:CStore_GetLocalizedNameForTags_Response)
    private static final SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Response DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Response();
    }

    public static SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Response getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<CStore_GetLocalizedNameForTags_Response>
        PARSER = new com.google.protobuf.AbstractParser<CStore_GetLocalizedNameForTags_Response>() {
      public CStore_GetLocalizedNameForTags_Response parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new CStore_GetLocalizedNameForTags_Response(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CStore_GetLocalizedNameForTags_Response> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CStore_GetLocalizedNameForTags_Response> getParserForType() {
      return PARSER;
    }

    public SteammessagesStoreSteamclient.CStore_GetLocalizedNameForTags_Response getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CStore_GetLocalizedNameForTags_Request_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CStore_GetLocalizedNameForTags_Request_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CStore_GetLocalizedNameForTags_Response_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CStore_GetLocalizedNameForTags_Response_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CStore_GetLocalizedNameForTags_Response_Tag_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CStore_GetLocalizedNameForTags_Response_Tag_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n%steammessages_store.steamclient.proto\032" +
      ",steammessages_unified_base.steamclient." +
      "proto\"J\n&CStore_GetLocalizedNameForTags_" +
      "Request\022\020\n\010language\030\001 \001(\t\022\016\n\006tagids\030\002 \003(" +
      "\r\"\237\001\n\'CStore_GetLocalizedNameForTags_Res" +
      "ponse\022:\n\004tags\030\001 \003(\0132,.CStore_GetLocalize" +
      "dNameForTags_Response.Tag\0328\n\003Tag\022\r\n\005tagi" +
      "d\030\001 \001(\r\022\024\n\014english_name\030\002 \001(\t\022\014\n\004name\030\003 " +
      "\001(\t2\307\001\n\005Store\022\230\001\n\027GetLocalizedNameForTag" +
      "s\022\'.CStore_GetLocalizedNameForTags_Reque",
      "st\032(.CStore_GetLocalizedNameForTags_Resp" +
      "onse\"*\202\265\030&Gets tag names in a different " +
      "language\032#\202\265\030\037A service to access store " +
      "data.B\003\200\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          SteammessagesUnifiedBaseSteamclient.getDescriptor(),
        }, assigner);
    internal_static_CStore_GetLocalizedNameForTags_Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CStore_GetLocalizedNameForTags_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CStore_GetLocalizedNameForTags_Request_descriptor,
        new java.lang.String[] { "Language", "Tagids", });
    internal_static_CStore_GetLocalizedNameForTags_Response_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_CStore_GetLocalizedNameForTags_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CStore_GetLocalizedNameForTags_Response_descriptor,
        new java.lang.String[] { "Tags", });
    internal_static_CStore_GetLocalizedNameForTags_Response_Tag_descriptor =
      internal_static_CStore_GetLocalizedNameForTags_Response_descriptor.getNestedTypes().get(0);
    internal_static_CStore_GetLocalizedNameForTags_Response_Tag_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CStore_GetLocalizedNameForTags_Response_Tag_descriptor,
        new java.lang.String[] { "Tagid", "EnglishName", "Name", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(SteammessagesUnifiedBaseSteamclient.methodDescription);
    registry.add(SteammessagesUnifiedBaseSteamclient.serviceDescription);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    SteammessagesUnifiedBaseSteamclient.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
